### ISSUE TITLE
language bar in SEB not working

### ISSUE THREAD

**Issue by webers-technikum-wien** [SafeExamBrowser/seb-win#1]
I tried out the language bar feature in the latest version of SEB (2.1.5682.30458), and while i do get the language bar in the bottom of SEB, switching input language there has no effect on what i type within SEB.

Is this a known issue? Happens both with normal users at the installations in our computer rooms, as well as for me on my work PC with full admin rights.

**Comment by danschlet** [comment]
Yes, unfortunately it doesn't work when running SEB 2.1 on Windows 7. We will fix this bug in SEB 2.1.1.

**Comment by webers-technikum-wien** [comment]
ah, that explains it. when do you think 2.1.1 will be available?

**Comment by pawy** [comment]
The Bug is fixed for Win7,8,10.
You can try the unstable Version here: https://github.com/SafeExamBrowser/seb-testing/tree/master/win/2.1.1 or wait for the release of 2.1.1 (this should happen until the end of the week)
