### ISSUE TITLE
Starke Einschränkungen nach Installation von SEB

### ISSUE THREAD

**Issue by Maienfelder** [SafeExamBrowser/seb-win#10]
Einer meiner Studenten (einer von 50) hat auf seinem Notebook mit Windows 7 Professional erhebliche Probleme seit er SEB installiert hat.
Was empfehlen Sie?

Problem 1:
Ich kann beim Anmelden kein @ Zeichen machen. Nach dem Abmelden und in einem anderen Programm das Zeichen machen und wieder Programm starten klappt es dann auch.
 
Problem 2:
Wenn ich im Programm bin, zeigt es mir die untere Taskleiste nicht an. Sie ist einfach komplett weiss und wenn ich mit dem Cursor darauf fahre, zeigt es an das es lädt. Sprich wenn ich das Programm beenden will muss ich es über das rote Kreuz oben rechts machen. Dies klappt auch und dann kann ich das Passwort eingeben und das Programm schliesst.
 
Problem 3: 
Sobald das Programm beendet ist, zeigt Windows meinen Desktop an nur ohne Icons und ohne die Taskleiste unten. Will ich den Taskmanager starten, dann öffnet es zwar den blauen Screen doch ich kann nichts auswählen ausser abbrechen.  Anschliessend bleibt mir nichts übrig als den Laptop abzuwürgen. 
 
Problem 4: 
Seit dem ersten Einsatz von SEB, kann ich den Laptop nicht mehr direkt von meinem Profil aus herunterfahren. Ich kann nur mich abmelden oder den PC sperren.

**Comment by danschlet** [comment]
Der Student sollte den "SEB Registry Resetter" benutzen, welcher die entsprechenden Optionen im "Windows Security Screen" (Ctrl-Alt-Del) und im System wieder freischaltet. Wie dieses Hilfsprogramm bedient wird, ist [auch hier](http://safeexambrowser.org/windows/win_usermanual_en.html#RegistryPane) (auf Englisch) beschrieben:

Registry Resetter ausführen, indem mit der rechten Maustaste im Kontextmenü "Als Administrator ausführen" gewählt wird. Der Registry-Resetter findet sich vom Programmverzeichnis ausgehend hier:
SafeExamBrowser\SebWindowsServiceWCF\SebRegistryResetter.exe
Im Registry Resetter muss zunächst "Y" eingegeben werden und danach der Kurzname des Windows-Benutzers, welcher SEB ausgeführt hat. Der Kurzname ist identisch mit dem Namen des Benutzerverzeichnisses des eingeloggten Benutzers.

Danach sollte der Registry Resetter alle Werte auf den Ursprungszustand setzen, so dass alle Optionen bei Ctrl-Alt-Del vorhanden sind und das Herunterfahren sollte dann wieder wie zuvor funktionieren.

Die beschriebenen Fehler treten leider selten auf einzelnen wenigen Rechnern auf, wir hoffen, dass das zugrunde liegende Problem in dem nächsten grösseren Update SEB 2.2 beseitigt sein wird. Ich würde bis dann empfehlen, dem betreffenden Studenten einen Ersatzrechner bereitzustellen. Wir empfehlen bei Prüfungen mit studentischen Geräten immer 5-10% Ersatzgeräte bereitzuhalten (auch abhängig davon, ob alle Prüfungskandidaten zuvor SEB erfolgreich installieren und testen konnten, wofür idealerweise eine Probeprüfung verwendet werden sollte).

**Comment by Cramery** [comment]
Hatte das selbe Problem, doch auch der Resetter funktionierte nicht. Ich erhalte blos die Meldung, dass nichts gefunden wurde, was geändert wurde. Doch ich kann keine Tastenkombinationen mehr benutzen, der Task-Manager funktioniert komplett nicht und ich bin kein Administrator mehr auf meinem Rechner....

**Comment by danschlet** [comment]
Versuchen Sie den SEB Registry Resetter der Testing-Version von SEB 2.2, welcher eine zuverlässigere Methode zum Rücksetzen der Registry-Werte benutzt. Installieren Sie SEB 2.2, den Sie hier herunter laden können: https://github.com/SafeExamBrowser/seb-testing/raw/master/win/2.2pre/SafeExamBrowser.msi
Am besten deinstallieren Sie die ältere SEB-Version zuvor im Windows-Kontrollfeld.

Ansonsten sind Ihre Angaben unverständlich für uns, was bedeutet "ich kann keine Tastenkombinationen mehr benutzen" (welche Tastenkombinationen?). 
"ich bin kein Administrator mehr auf meinem Rechner" SEB kann keine Benutzerrechte ändern. Habe Sie mehrere Benutzerkonten auf ihrem Computer und Sie können sich nicht nur noch mit dem normalen Benutzer einloggen und nicht mit dem Administrator? So einen Fehler hat uns noch niemand zuvor gemeldet, trotz mehr als einer halben Million Prüfungen mit SEB im Jahr 2016...
