### ISSUE TITLE
Download and open file is not working

### ISSUE THREAD

**Issue by Gendie** [SafeExamBrowser/seb-win#100]
**Description**
Although I configured the Safe exam browser to download and open files. when clicking a download link and confirm to save the file. Nothing changes. No loader or notification that download is in-progress. 
I don't know if the download doesn't start or it starts but no loader or notification.

**Steps to Reproduce**
1- At the General tab. set the **Start URL** to any website that has download link. 
Example: https://sourceforge.net/projects/seb/
2- At Down/Uploads tab. Select **Allow downloading and uploading files**. and Select **Open files after download**.
3- Run the Safe exam browser using this settings. And click the Download link.

**Expected Behavior**
Show download confirmation and if "Save File" is clicked. it should display an indication that the download is in-progress then open the downloaded file.

**Actual Behavior**
Download confirmation is displayed. but when click "Save file" nothing happens.

**Version Information**
 - OS: Windows 10 Professional
 - SEB-Version SEB 2.4.1

**Comment by dbuechel** [comment]
Thanks for your report. SEB 2.x is no longer actively developed, we thus won't be able to solve this issue and highly recommend you using the latest version of SEB 3.x: https://github.com/SafeExamBrowser/seb-win-refactoring/releases. Should you encounter the same problem with SEB 3.x as well, please feel free to report it again under https://github.com/SafeExamBrowser/seb-win-refactoring/issues.
