### ISSUE TITLE
I can't access webcam

### ISSUE THREAD

**Issue by 81718** [SafeExamBrowser/seb-win#106]
# ~ISSUE TITLE HERE~

**IMPORTANT**
Please _always_ consult the documentation first before creating an issue!
https://safeexambrowser.org/windows/win_usermanual_en.html

### Description

~YOUR ISSUE DESCRIPTION HERE...~

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: X.X(.X) \
SEB-Version: X.X(.X)

### Steps to Reproduce

1. ~INSTRUCTION STEP 1~
2. ~INSTRUCTION STEP 2~
3. ~...~

> ***Information:** 
Please replace all placeholders (~PLACEHOLDER~) and version numbers according to your situation. The more detailed information you provide, the easier it will be for us to detect and reliably fix the issue. Feel free to delete this comment before submitting the issue report...*

**Comment by dbuechel** [comment]
Thanks for your report. SEB 2.x is no longer actively developed, we thus won't be able to solve this issue and highly recommend you using the latest version of SEB 3.x: https://github.com/SafeExamBrowser/seb-win-refactoring/releases. Should you encounter the same problem with SEB 3.x as well, please feel free to report it again under https://github.com/SafeExamBrowser/seb-win-refactoring/issues.
