### ISSUE TITLE
[Question] Checking Authenticity of Third Party Applications in Unmanaged PCs

### ISSUE THREAD

**Issue by cemonem** [SafeExamBrowser/seb-win#107]
# Checking Authenticity of Third Party Applications in Unmanaged PCs

### Description

Hello,
Is it possible to check the authenticity of the allowed third party applications within Safe Exam Browser (by checking if the md5sum of the executable matches the one in the configuration file etc.)? Although the configuration of the browser is enforced with the browser exam keys and the moodle plugin, it seems that one can cheat by replacing the allowed executable with another application with the same name, even though that application may not be permitted during the exam.

### Environment & Version

Windows 10

- [ ] Mac
- [x] Windows

SEB-Version: 3.0.1

**Comment by dbuechel** [comment]
Yes, you can define an original name for each application executable which you define in the configuration. We might extend this in the future to also enable validation by a checksum or alike, although that would require a change to the configuration every time an application is updated.
