### ISSUE TITLE
SEB 2.4.1 not loading PWA offline

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/seb-win#108]
I am having problems with offline service-workers in SEB-2.4.1, and I am not sure if it is my code, SEB, or how to debug the problem.

The service worker works offline (with network switched off) in Chrome, Firefox, Safari and Edge. In SEB, if the site loads online, and then the network is switched off, the page keeps working, and can be reloaded whilst offline.

However if I quit and restart SEB whilst offline the site does not load, and SEB has just a plain white page with the control bar at the bottom. 

Clicking 'reload' whist offline like this results in a dialog that says "The connection was refused when attempting to contact ***."

Re-enabling WiFi and clicking reload in SEB does load the page.

How can I get my app to start in SEB whilst offline?

**Comment by dbuechel** [comment]
Thanks for your report. SEB 2.x is no longer actively developed, we thus won't be able to solve this issue and highly recommend you using the latest version of SEB 3.x: https://github.com/SafeExamBrowser/seb-win-refactoring/releases. Should you encounter the same problem with SEB 3.x as well, please feel free to report it again under https://github.com/SafeExamBrowser/seb-win-refactoring/issues.
