### ISSUE TITLE
opening seb link failed. check your internet connection and try again

### ISSUE THREAD

**Issue by michkleee** [SafeExamBrowser/seb-win#109]
Hello I have a problem with my SEB. Everytime i open it, it says "Opening the SEB link failed. Check your internet connection and try again," even when the internet connection is perfectly fine. After that, it lets me log in to my account for moodle but then when I try to open my quiz it wont let me, it will just show a white popup box saying reconfiguration. I am using the Windows Legacy version 2.4.1 for windows. My os is windows 10. Please help me and tell me what I did wrong while installing/configuring, I need this o work by tomorrow, I still have to study for the exams on monday :(( thank you
@danschlet @eqsoft @pawy @rehlert-kk @dbuechel

**Comment by dbuechel** [comment]
Thanks for your report. SEB 2.x is no longer actively developed, we thus won't be able to solve the issue and highly recommend you using the latest version of SEB 3.x: https://github.com/SafeExamBrowser/seb-win-refactoring/releases. Should you encounter the same problem with SEB 3.x as well, please feel free to report in that repository there again.
