### ISSUE TITLE
Maus abgehängt?

### ISSUE THREAD

**Issue by lucaboesch** [SafeExamBrowser/seb-win#11]
Liebes SEB-Team

Ich gebe euch eine Rückmeldung weiter, ohne sie näher nachgeprüft zu haben, e.g. handelt es sich um eine USB-Maus, um ein Trackpad?

Anyway:

> Jetzt ist etwas sehr seltsames passiert. Bei zwei PCs (wenn ich mich korrekt erinnere waren beide von „Dell“) hat der SEB auch gerade die Maus blockiert. Das habe ich  jetzt zum ersten Mal erlebt und ich frage mich, ob das mit der neuen SEB-Version zu tun hat.
 
Vielen Dank,

Luca

**Comment by danschlet** [comment]
Wir bräuchten mehr Informationen und/oder einen Kontakt zu derjenigen Person, die das Problem direkt beobachtet hat. So können wir leider nichts anfangen mit diesem Issue-Report.

**Comment by lucaboesch** [comment]
Ich kümmere mich darum!

**Comment by danschlet** [comment]
Wichtig zu wissen wäre:
- Welche Windows-Version wurde verwendet?
- Welche SEB-Version?
- War das eine reine Browser-Prüfung oder wurden in SEB zugelassene Drittapplikationen in der Prüfung benutzt?
- Was heisst “Maus blockiert”? Hat sich der Mauscursor überhaupt nicht mehr bewegt? Konnte man SEB aber noch irgendwie beenden (Ctrl+Q ausprobiert?). War das eine externe Maus oder ein eingebautes Trackpad?
- In welcher Situation ist das passiert, direkt nach dem Starten von SEB? Mitten während einer Prüfung mit SEB? Beim Beenden von SEB?
- Ist das Problem reproduzierbar, also passiert es immer in einer bestimmten Situation?
- und alle Informationen, die uns helfen, das Problem zu verstehen und im Idealfall zu reproduzieren.

Abhängig von den Antworten auf diese Fragen könnten uns eventuell die SEB-Logdateien helfen, im Handbuch ist beschrieben, wo man diese findet:
http://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane

**Comment by danschlet** [comment]
Der Grund für dieses Problem ist hier beschrieben (auf Englisch): [SEB Bugs#68](https://sourceforge.net/p/seb/bugs/68/)

Durch Umschalten auf den "Disable Explorer Shell" Kiosk-Modus kann das Problem gelöst werden. Allerdings müssen dazu die lokalen Client-Einstellungen geändert werden, ansonsten können keine SEB-Konfigurationen für Prüfungen mit dem "Disable Explorer Shell" Kiosk-Modus benutzt werden.

Das Problem kann umgangen werden, wenn die Bildschirmskalierung in den Windows-Einstellungen auf 100% gestellt wird bevor SEB benutzt wird. Wenn die Bildschirmanzeige dann zu klein erscheint, kann temporär auf eine kleinere Auflösung umgeschaltet werden.

Wir arbeiten an SEB-Updates, welche dieses Problem direkt lösen werden.
