### ISSUE TITLE
Red Screen on Startup - Lost Connection to SEB Kiosk Application

### ISSUE THREAD

**Issue by pfurches** [SafeExamBrowser/seb-win#110]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
When starting SEB 2.40, 2.41 or 3.1 on a hotspot connection the screen turns red and the following error is displayed.
Lost Connection to SEB Kiosk Application

**Steps to Reproduce**
1. Connect to a wi-fi hotspot.
2. Launch SEB. Version 2.40, 2.41 and 3.1 all do the same thing so we are using 3.1.
3. Red screen appears with error. Then asks for password to unlock.

**Expected Behavior**
SEB testing site should open for user to login.

**Screenshots**
![20201119_112052](https://user-images.githubusercontent.com/7400863/99693657-9f6b5700-2a59-11eb-9cb9-e45783b0c1d5.jpg)

**Version Information**
 - OS: Windows 10 2004 and Windows 10 2009
 - SEB-Version 3.1.0

**Additional Context**
We use a PAC file for filtering and have added all known exceptions and excluded SSL inspection for the same URLs.
These are cleanly imaged devices with no other software installed on them and all current Windows updates.

**Comment by dbuechel** [comment]
This issue cannot affect SEB 3.x, as there the browser is integrated in SEB itself, i.e. this lock screen message doesn't exist in SEB 3.x. Regarding your issue, SEB 2.x communicates with the separate browser application via a websocket connection on localhost. If you're using proxies and / or firewalls, make sure that you allow those connections.

**Comment by pfurches** [comment]
The screen shot you are seeing is from version 3.1.0.228 so I have to disagree. It is happening on 3.1 right now and I can duplicate the issue on hundreds of devices.

**Comment by dbuechel** [comment]
I'm sorry, that cannot be correct. I literally wrote the entire code of SEB 3.x and am perfectly certain that this error message only exists in SEB 2.x. When reporting a bug, it is imperative that the provided information is accurate, otherwise it is hard for us to efficiently track down issues...

**Comment by pfurches** [comment]
I just verified Program Files\SafeExamBrowser\SafeExamBrowser.exe is version of 3.1.0.228.
Would you like to remote into the device and see it yourself?

**Comment by pfurches** [comment]
So I am looking at this and it looks like remnants of 2.41 are still on the system and did not remove when the 3.1 MSI ran. I am removing everything and rebooting and trying again. At least the service from 2.41 are still installed.
