### ISSUE TITLE
Will I be able to compile from source or are only precompiled versions functional?

### ISSUE THREAD

**Issue by Alex-Programs** [SafeExamBrowser/seb-win#118]
# Will I be able to compile from source or are only precompiled versions functional?

### Description

Being able to read the source has eased my fears about letting this run on my device. However, I do not want to be accused of cheating because I compiled my own version. If I compile the software from source, will it act the same as one of your releases? Or does the version you distribute have changes that I need to complete a test?

**Comment by danschlet** [comment]
If you compile your own version, the code signature will differ and depending on how the test is set up, it won't accept your own compiled version.

We understand students which want to know what software is running on their own computer, this is one reason why SEB is open source. But you also have to understand that we cannot recommend teachers/universities/schools to accept self-compiled versions of SEB for exams, as such versions could break the security of the lockdown browser. See also our [Privacy Statement](https://safeexambrowser.org/about_overview_en.html#privacy-statement) (SEB doesn't connect to any centralized servers/clouds).

**Comment by Alex-Programs** [comment]
What good is it being open source if only your precompiled versions run? How do I know you haven't changed anything? @danschlet

**Comment by danschlet** [comment]
A really experienced developer can compare the binaries easily.

But maybe you don't understand that a secure lockdown browser is used to ensure fairness in exams (amongst other reasons). You can discuss this with your professor/teacher/university legal representative. We just provide the software for free and to be honest such discussions don't belong here, it's not a idealogical thing for us.

**Comment by Alex-Programs** [comment]
OK, then I'll be comparing the binaries.

**Comment by danschlet** [comment]
I can understand that you don't know if you can trust Safe Exam Browser, but I can assure you that ETH Zurich, the public Swiss university where we are based at would not allow us to publish any malicious spyware software: https://en.wikipedia.org/wiki/ETH_Zurich

I wonder if you trust Microsoft more or do you compile Windows also yourself?

**Comment by Alex-Programs** [comment]
I would rather run Linux, but then you don't support it.

Does this project have reproducible builds?

**Comment by danschlet** [comment]
I leave this to our Windows developer to answer @dbuechel. But I really don't think you are spending your time wisely. You can't trust any software, even open source software can contain cleverly hidden unexpected code, as some coding challenges prove. 

Why are you not just checking if SEB connects to some centralized server? That's the biggest risk with software nowadays. 

Anyways, I'm stopping to waste my time with this discussion. Have a good day/life!
