### ISSUE TITLE
Prohibited processn locked

### ISSUE THREAD

**Issue by sueda-v** [SafeExamBrowser/seb-win#119]
![WhatsApp Image 2021-03-25 at 12 33 10](https://user-images.githubusercontent.com/81356625/112451298-65db8d00-8d66-11eb-855e-997e2905ebd1.jpeg)
***the bug***
when I take the exam, it gives a red screen and asks for a code.
the application works as an administrator, the firewall is turned off, and the back gives a red screen, even though no other application is running

**version information**
Safe Exam Browser 2.3.1 for MacOs

**Comment by dbuechel** [comment]
You'd need to post this issue in the SEB for macOS repository.
