### ISSUE TITLE
Unable to click anywhere with the mouse

### ISSUE THREAD

**Issue by linneaang** [SafeExamBrowser/seb-win#12]
Hi,
I have a microsoft surface pro 4 and when I launched a demo exam today I couldn't click anywhere. I re-
installed the latest version of SEB today but that didn't help. I'm able to use the other buttons on the keyboard and I can use enter for clicking in the exam, and I can move the mouse but doesn't get any repsones when clicking. I have windows 10 on my computer. I've been doing exams digitally on my computer before with no problems.

**Comment by danschlet** [comment]
The reason for this sudden problem is a Windows update. Please tell your exam administrator to have a look at the solution pointed out here: [SEB Bugs#68](https://sourceforge.net/p/seb/bugs/68/)

In the meantime you could try to set your screen scale to 100% before using SEB and maybe also change the screen resolution (if screen content gets too small with the 100% scale). This seemed to have helped several people as you can see in the bug report.

**Comment by danschlet** [comment]
This was fixed with a workaround in SEB 2.1.6, proper solution in SEB 2.1.8. It was definitely a bug introduced by Microsoft in a Creator's Update.
