### ISSUE TITLE
When I install program this proplem happened

### ISSUE THREAD

**Issue by Abdelkaderof** [SafeExamBrowser/seb-win#120]
![IMG-20210329-WA0000](https://user-images.githubusercontent.com/81537284/112770327-905b6d80-9026-11eb-96fa-f58b2ac57c79.jpg)
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Version Information**
 - OS: [e.g. Windows 10 Professional, Version 1803]
 - SEB-Version [e.g. SEB 2.2.2]

**Additional Context**

**Comment by dbuechel** [comment]
Try updating your system, restart it and run the setup again.
