### ISSUE TITLE
unable to allow front camera to click the picture while using SafeExamBrowser...please give me answer.

### ISSUE THREAD

**Issue by samimsamu** [SafeExamBrowser/seb-win#13]

**Comment by dbuechel** [comment]
Hi there

Unfortunately, we cannot help you with as little information as you provided. There is a reason why we created an issue template, and if you would like us to help you, you'd need to invest the time required and fill it out properly...

Here's the template again, in case you didn't see it:
[https://github.com/SafeExamBrowser/seb-win/blob/master/.github/ISSUE_TEMPLATE.md](https://github.com/SafeExamBrowser/seb-win/blob/master/.github/ISSUE_TEMPLATE.md)
