### ISSUE TITLE
Unable to take snapshot using front camera in SafeExamBrowser

### ISSUE THREAD

**Issue by samimsamu** [SafeExamBrowser/seb-win#14]
Unable to take snapshot using front camera in SafeExamBrowser

### Description

I have developed in house an Online Assessment Platform with camera features such as for clicking the picture of students while Log In to the test  and for freezing the browser we are using SEB but camera feature is disabled...please guide me is there any feature on SEB where I can allow the camera button to click the picture.

### Environment & Version
Hp , RAM 8GB, HD- 500GB

- [x] Windows

OS-Version: 8 and 10
SEB-Version: 2.1.3

**Comment by dbuechel** [comment]
Hi there

This is unfortunately an issue that the current SEB does not support. If you implemented the access to the web camera with HTML5, you'll need to manually disable the setting `media.navigator.permission.disabled` in the browser engine of SEB (per runtime).
If possible, you could consider using a third-party application to observe students during an exam and allow said application in the SEB exam configuration.

I'm sorry that I can't help you any further here.
Regards,
Damian
