### ISSUE TITLE
SEB launch concerns

### ISSUE THREAD

**Issue by visaac** [SafeExamBrowser/seb-win#15]
Good morning Damian, 

I followed the instructions from the previous email you sent me to end the processes of the SEB in the task manager, but the program will not launch simultaneously. The error message, "Seb is already running, but is not responding. The old web process must be closed to open a new window", still appears.
Best Regards,

Valerie Isaac
 Information Technology Technician I
 visaac@allenuniversity.edu

**Comment by dbuechel** [comment]
Hi Valerie

It appears then that the process of the browser component of SEB has crashed. To end it, terminate the process with name "xulrunner.exe" via the task manager, as previously described.

Cheers,
Damian

**Comment by visaac** [comment]
Will it launch the program on multiple computers when I complete this step?

**Comment by danschlet** [comment]
I don't understand your issue, you said you installed SEB on 64 PCs and it worked, but on another location it didn't. What did you exactly do in the latter case?

Just to mention: There can only be one instance of SEB running on a system. In case you use Windows Server or another terminal server, where SEB would run simultaneously for several users on the same physical machine, this won't work and could produce similar error messages.

**Comment by visaac** [comment]
I had no problem installing the SEB. My issue occurs when I launch the program, I want to be able to open it at the same time on more than one computer so that students can test. It works for 64 of the computers, but the other 29 don't.

Sent from my MetroPCS 4G LTE Android device

On Jul 28, 2017 1:40 PM, "Daniel R. Schneider" <notifications@github.com> wrote:

I don't understand your issue, you said you installed SEB on 64 PCs and it worked, but on another location it didn't. What did you exactly do in the latter case?

Just to mention: There can only be one instance of SEB running on a system. In case you use Windows Server or another terminal server, where SEB would run simultaneously for several users on the same physical machine, this won't work and could produce similar error messages.

**Comment by visaac** [comment]
Any update on the SEB launching on different computers at the same time?

**Comment by dbuechel** [comment]
Hi Valerie

I assume you were able to resolve the issue concerning the error message "Seb is already running, but is not responding."? For your second problem, we would need to have some more information: What are you trying to do when you say "I'm trying to open SEB at the same time on more than one computer"? Are you using managed clients or alike? How exactly are you starting SEB remotely, what is your network / infrastructure setup?

Cheers,
Damian

**Comment by visaac** [comment]
Hello,


We plan on using SEB to administer our placement test for incoming freshmen. I want to be able to launch the browser on each computer at the same time without having to log on/off one by one. That's the problem I am having. When I click on the Icon to launch the browser, it won't allow me to open it up more than one time. I am not working remotely. Everything is on site.


Valerie Isaac

Information Technology Technician I

Allen University

1530 Harden Street

Columbia, SC 29204

(803) 376-5903 office

(803)-297-9874 cell

visaac@allenuniversity.edu


"Don't let anyone turn your sky into a ceiling".

________________________________

**Comment by danschlet** [comment]
But how are you opening SEB on each computer? When you say you're not working remotely, does that mean you walk from one computer to the next and start SEB manually there? I guess not, you must be using some tool to start SEB on these computers?

**Comment by visaac** [comment]
Yes, I walk from one to another and start it manually.

Sent from my MetroPCS 4G LTE Android device

On Aug 2, 2017 1:03 PM, "Daniel R. Schneider" <notifications@github.com> wrote:

But how are you opening SEB on each computer? When you say you're not working remotely, does that mean you walk from one computer to the next and start SEB manually there? I guess not, you must be using some tool to start SEB on these computers?

**Comment by danschlet** [comment]
Well, then I still don't understand what isn't working. SEB gets installed on each computer, isn't it? Then a student starts SEB on that computer, performs the exam, SEB is quit after the exam (ideally using a Quit Link) and then the next student can start SEB again. Where in this process is it that you "want to be able to launch the browser on each computer at the same time without having to log on/off one by one"? I just don't understand that sentence. Try to describe exactly step-by-step what you're trying to do and which of these steps doesn't work.

**Comment by visaac** [comment]
Step 1. Install SEB
Step 2. Open SEB config tool. Follow configuration steps.
Step 3. Launch browser ( step doesn't work simultaneously)
The problem I am having with Step 3 is I want the students to be able to launch SEB at the same time on different computers so that they can start the test.

Sent from my MetroPCS 4G LTE Android device

On Aug 2, 2017 1:25 PM, "Daniel R. Schneider" <notifications@github.com> wrote:

Well, then I still don't understand what isn't working. SEB gets installed on each computer, isn't it? Then a student starts SEB on that computer, performs the exam, SEB is quit after the exam (ideally using a Quit Link) and then the next student can start SEB again. Where in this process is it that you "want to be able to launch the browser on each computer at the same time without having to log on/off one by one"? I just don't understand that sentence. Try to describe exactly step-by-step what you're trying to do and which of these steps doesn't work.

**Comment by visaac** [comment]
Is there a number I can call to explain to you over the phone exactly what I mean? If you're near a computer I can show you.

Sent from my MetroPCS 4G LTE Android device

On Aug 2, 2017 1:25 PM, "Daniel R. Schneider" <notifications@github.com> wrote:

Well, then I still don't understand what isn't working. SEB gets installed on each computer, isn't it? Then a student starts SEB on that computer, performs the exam, SEB is quit after the exam (ideally using a Quit Link) and then the next student can start SEB again. Where in this process is it that you "want to be able to launch the browser on each computer at the same time without having to log on/off one by one"? I just don't understand that sentence. Try to describe exactly step-by-step what you're trying to do and which of these steps doesn't work.

**Comment by danschlet** [comment]
Of course it is possible to start SEB on different, independent computers. I still don't understand why that doesn't work for you. I hope you understood that you have to create a SEB config file once (on your "administrator" computer and use that file to configure SEB on all the exam computers?
If you do this according to our documentation, then of course you can run SEB at the same time on all exam computers. SEB isn't using any kind of centralized service running on a server or in the cloud, besides of course the online quiz running on your exam server (which address you configure as "Start URL").
If you really cannot start SEB on more than one of your exam computers at the same time then they are in fact sharing some parts of Windows or their file systems without you realizing it. Talk with your IT department staff in this case.

**Comment by visaac** [comment]
Okay thank you very much for your help.

Sent from my MetroPCS 4G LTE Android device

On Aug 2, 2017 1:46 PM, "Daniel R. Schneider" <notifications@github.com> wrote:

Of course it is possible to start SEB on different, independent computers. I still don't understand why that doesn't work for you. I hope you understood that you have to create a SEB config file once (on your "administrator" computer and use that file to configure SEB on all the exam computers?
If you do this according to our documentation, then of course you can run SEB at the same time on all exam computers. SEB isn't using any kind of centralized service running on a server or in the cloud, besides of course the online quiz running on your exam server (which address you configure as "Start URL").
If you really cannot start SEB on more than one of your exam computers at the same time then they are in fact sharing some parts of Windows or their file systems without you realizing it. Talk with your IT department staff in this case.
