### ISSUE TITLE
Double installation

### ISSUE THREAD

**Issue by kfahringer** [SafeExamBrowser/seb-win#16]
Double installation

### Description

I work in a testing center and we have two exam systems using SafeExam Browser for administration.  Each exam requires different configurations.  Is there a way to install SafeExam Browser twice each with different configurations.

### Environment & Version

Windows
- [ ] Mac
- [x] Windows

OS-Version: X.X(.X) \
SEB-2.1.3

### Steps to Reproduce

1. ~INSTRUCTION STEP 1~
2. ~INSTRUCTION STEP 2~
3. ~...~

> ***Information:** 
Please replace all placeholders (~PLACEHOLDER~) and version numbers according to your situation. The more detailed information you provide, the easier it will be for us to detect and reliably fix the issue. Feel free to delete this comment before submitting the issue report...*

**Comment by danschlet** [comment]
No, you can only install one instance per computer. But you can use various settings, as SEB can reconfigure itself when a seb(s):// link to a .seb config file is clicked. Read the documentation at http://safeexambrowser.org!
