### ISSUE TITLE
Windows settings issue after using SEB

### ISSUE THREAD

**Issue by akiirish** [SafeExamBrowser/seb-win#19]
I used the SEB for an exam today and now I am unable to put my computer to sleep/restart/etc or change the settings that would allow me to regain control of this option. Somehow, it appears I no longer have proper administrative control over my machine. I tried to use "SafeExamBrowser\SebWindowsServiceWCF\SebRegistryResetter.exe" but received an error that an administrator was required to run the file. This is incredibly annoying especially considering the given the 10-20 sec lag between each question that made my exam a living nightmare. Please advise how to return my PC to its prior state ASAP.

Regards

Asus Laptop, running Win10

**Comment by danschlet** [comment]
The lag between your questions in that exam is definitely not SEB's fault, but probably your exam provider's server or the network had some issues.

You have to right click SebRegistryResetter.exe and select from the context menu "Run as administrator", even if you are using an administrator account. This is a common Windows feature. 

How to use Registry Resetter is explained in the [SEB manual](http://safeexambrowser.org/windows/win_usermanual_en.html#RegistryPane).

Regards

**Comment by akiirish** [comment]
Okay, I ran it as an Administrator. It appeared to do something but my computer is still screwed up. I don't know that much about computers and I need some help here. Is there a support number? I just want my computer back to how it was before this SEB was installed.

**Comment by danschlet** [comment]
Please make sure to follow the instructions from the manual correctly:

You need to execute this tool as administrator (right mouse button context menu "Run as administrator"). In case the original values for the Registry Settings aren't found anymore, they will be reset to the Windows default values (all enabled). In this latter unlikely case **you would also need to enter the short user name of the user in which account SEB was run**, when the problem occurred. If you were running SEB in your administrator account, the short user name you have to enter usually isn't "Admin" or similar. It is the user name of the account which has the administrator role. **The short user name is the same as the name of the user's home directory (if you go to C:\Users\ in a Windows Explorer window, you can see all user account names on this computer).** If you have spaces in your short user name, enter it as it is, without quotes.

See [this discussion thread](https://sourceforge.net/p/seb/discussion/3704033/thread/23b0c2e5/?limit=25#7d79) for more information and [this screenshot](https://sourceforge.net/p/seb/discussion/3704033/thread/23b0c2e5/7d79/attachment/Screen%20Shot%202016-06-10%20at%2017.23.27.png) how the output of the Registry Resetter should look.

If this still doesn't work, then [download](https://github.com/SafeExamBrowser/seb-testing/raw/master/win/2.2pre/SafeExamBrowserInstaller.exe) and install the preview version of SEB 2.2 and run its Registry Resetter, which has been improved and should work in the rare cases when older versions fail.

We don't have a support number, we only provide limited support on our project sites on GitHub and SourceForge. SEB is freeware open source software. It is provided for free, but also [without any kind of warranty](https://www.mozilla.org/en-US/MPL/1.1/). Your university or school who let you use SEB for an exam has to provide support to you. So talk with them if your computer still isn't working as before.

**Comment by akiirish** [comment]
Ah, the 2.2 version did it. Thanks!
