### ISSUE TITLE
Silent Install Paramters Ignored?

### ISSUE THREAD

**Issue by schuhj** [SafeExamBrowser/seb-win#2]
Having some issues with automatic deployment of SEB:

`SafeExamBrowserInstaller.exe /?`
Opens a Help dialog stating: "For silent mode use: /S /v /qn"

But `SafeExamBrowserInstaller.exe /S /v /qn` starts the normal interface and waits for user interaction.

I currently use the extracted .msi file from C:\ProgramData\Downloaded Installations{...} with the `/qb!` switch.

Some documentation on silent deployment would be helpful (maybe I missed it?).

**Comment by danschlet** [comment]
We didn't support silent mode until now, looks like InstallShield needs some special configuration for this to work in the created SEB installer.

The next major update (expected to release sometimes this summer) will have a new WiX-based installer which creates a .msi file. We'll make sure silent mode works there.

**Comment by markben77** [comment]
Along the lines of silent install - is there a way to build as a zip file instead of the .msi?

**Comment by danschlet** [comment]
Do you really think we would bother to create an installer if it wouldn't be necessary? If you want an archive containing an executable which you can just copy somewhere and start, then you would need to use a Mac and not a Windows PC. The installer inside the .msi has to register the .seb file type, seb:// URL protocol and install the SEB Windows service (described in the [manual](http://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane)).

**Comment by bodrick** [comment]
If you want to do a silent install use the following command line
`SafeExamBrowserInstaller /s /v" /qn"`
Be sure to include the extra quotes, this worked for me with the latest version.
