### ISSUE TITLE
SSL Certificates without CN attribute cause Runtime Exception in SebWindowsConfig

### ISSUE THREAD

**Issue by mhandschuh** [SafeExamBrowser/seb-win#21]
SSL Certificates without CN attribute cause Runtime Exception in SebWindowsConfig

### Description

If you have an SSL Certificate inside your Certificate Store which doesn't have a CN attribute SebWindowsConfig Tool crashes.

### Environment & Version
- [ ] Mac
- [x] Windows

OS-Version: Windows 7
SEB-Version: 2.1.7

### Steps to Reproduce
Error is thrown in  seb-win/SebWindowsClient/SebWindowsClient/CryptographyUtils/SEBProtectionController.cs  on Line 160: certificateNames.Add(Parse(x509Certificate.Subject, "CN").FirstOrDefault());
Because the Parse method can return null values
This can be fixed by checking for null value return before calling FirstOrDefault

**Comment by dbuechel** [comment]
Hi

Thanks for the detailed bug report. This issue will be fixed in the upcoming release of version 2.2.

Kind regards,
Damian
