### ISSUE TITLE
Permanenty disabled features in Windows

### ISSUE THREAD

**Issue by emilhem** [SafeExamBrowser/seb-win#28]
### Description
After having issues with Windows 10 and SEB it left the computer with Task Manager, shutdown, reboot, sleep, and hibernate features disabled.

### Environment & Version
Acer ES1-132-P2MZ
1.1GHz Intel Pentium
4GB RAM
Plenty of space left on disk

Windows 10
OS-Version: 10..0.15063
SEB-Version: 2.1.7

### Steps to Reproduce

Unsure since it just broke and isn't reproducible.

You should provide an executable to revert the lockdown in case SEB crashes.

I managed to recover Task Manager in RegEdit

**Comment by emilhem** [comment]
I found the terminal application to fix it.

**Comment by milos969** [comment]
There is still this issue happening, by running antivirus scan it could be fixed, but after a while it still breaks those power features. This should not be marked as closed...

**Comment by danschlet** [comment]
Which SEB version are you using?

In the just released SEB 2.2, we made some improvements and hope the issue won’t happen anymore. So make sure the options are all there when you press Ctrl+Alt+Delete and then install SEB 2.2. Let us know if the issue still happens.

You mentioned that an antivirus scan fixes the issue, which software are you using for that?

There is a SEB command line tool to restore the standard values, the SEB Registry Resetter, see here https://www.safeexambrowser.org/windows/win_usermanual_en.html#RegistryPane.

Emilhem found it and therefore closed the issue.

**Comment by milos969** [comment]
Thank you for the response, I recovered options. I used to manage this issue by performing scan with Malwarebytes, with the full version (not trial, it won't solve it ). I have updated SEB today to 2.2, hopefully it won't break those options anymore :D
