### ISSUE TITLE
SEB installer - file corrupted 

### ISSUE THREAD

**Issue by pajda777** [SafeExamBrowser/seb-win#3]
Hello,
There are two problems with installer:
1) When downloaded using Edge it says: "the signature of this program is corrupt or invalid" ,so file is not possible to open directly
2) When opened from windows 10 file system, it gives a smartscreen warning that this program can harm you computer.

Is it possible to do something with it ?

Thanks

**Comment by danschlet** [comment]
This happens when you have Windows internet security level set to the highest. Don't ask me why, the SEB installer (and all binaries and DLLs) are code signed with a proper certificate. We have to find out what kind of "enhanced" Microsoft-approved certificate you need so that Edge and Windows doesn't complain. 

Workaround: Use another browser to download SEB and ignore the warning. When the installer is started, you will see that it is code signed by ETH Zuerich.

**Comment by pajda777** [comment]
Well ,it will be difficult to explain this situation to our users (sometimes PC beginners).
I going to run Windows App Certification Kit to see if there will be something...

**Comment by pajda777** [comment]
Here are the result from WAC kit (not sure if it can help):

Digitally signed file test

WARNING

Install signed driver and executable files

All unsigned files of the following extensions: EXEs, DLLs, SYS, DRV, OCX, SCR, and CPL will be reported.

•Warning: The file, driver signing test detected the following errors: ◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\de\SafeExamBrowser.resources.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\gmp-fakeopenh264\1.0\fakeopenh264.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\gmp-fake\1.0\fake.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\gmp-clearkey\0.1\clearkey.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\xulrunner.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\xulrunner-stub.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\xul.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\wow_helper.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\updater.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\softokn3.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\sandboxbroker.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\redit.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\plugin-hang-ui.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\plugin-container.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\nssdbm3.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\nssckbi.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\nss3.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\mozglue.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\libGLESv2.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\libEGL.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\js.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\icuuc52.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\icuin52.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\icudt52.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\IA2Marshal.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\freebl3.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\crashreporter.exe does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\breakpadinjector.dll does not have a valid signature, either embedded or via a catalog file.
◦Non-driver file C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xulrunner\AccessibleMarshal.dll does not have a valid signature, either embedded or via a catalog file.
 If any of the above files are DLLs, OCX, SCR, CPL or EXEs that are not one of the application’s main executables (has a shortcut on start menu or desktop), they can safely be ignored. All others need to be signed to meet the Windows App Certification requirements. 
•Impact if not fixed:  Having digitally signed files allows users to know that software is genuine. It makes it possible to detect that a file has been tampered with, such as by a virus. Windows has the ability to prevent any unsigned app from launching with administrator access. Sign the app if you want it to operate correctly in locked-down environments without popup or UAC messages. 

•How to fix:  You can safely ignore the unsigned DLL, .OCX, .SCR, .CPL or .EXE files listed here that are not one of the app’s main executable, or a driver. All files except drivers must be Authenticode signed, drivers must be WHQL certified. See link below for more information: 
Digital Signatures for Kernel Modules on Windows

**Comment by pajda777** [comment]
Closing issue, version 2.1.3 resolved it.
