### ISSUE TITLE
Exit Dialog OK/Cancel Buttons Cutoff

### ISSUE THREAD

**Issue by randy-knapp** [SafeExamBrowser/seb-win#30]
# Exit Dialog OK/Cancel Buttons Cutoff

### Description

SEB Config file is configured to allow users to exit with passcode by clicking on X after launching SEB.     Close Safe Exam Browser dialog is displayed, however, OK and Cancel buttons are cutoff.   Functionality is fine, it's just the buttons are cutoff.    Attached screen shot shows cutoff dialog.
![20180110_135500](https://user-images.githubusercontent.com/5741346/34792906-31529584-f60f-11e7-8ac4-55ad8badfbc2.jpg)

### Environment & Version
Windows 7/10.   SEB version 2.1.8.1.
Dell Latitude E6540.

- [ ] Mac
- [x] Windows

OS-Version: Windows 7 or 10.  Either one has cutoff dialog.
SEB-Version: 2.1.8.1

### Steps to Reproduce

1. Just configure SEB to allow exit with passcode.
2. Run SEB and then try to exit.
3. Exit dialog with cutoff buttons is displayed.

**Comment by dbuechel** [comment]
This is a known issue, which should have been fixed (by me, actually). Are you sure you used the latest installer for SEB 2.1.8? I just tried to reproduce the problem, but was unable to do so (on Windows 7 and 10).
I remember that the problem happened when running SEB on a high-DPI monitor with a display scaling greater than 100%. Could you please post your display settings (resolution and scaling factor)? You could also try different scaling factors and see if the problem persists, or install the preview version of SEB 2.2 and check whether it still happens there, too. The installer for SEB2.2pre5 can be found here: https://github.com/SafeExamBrowser/seb-testing/blob/master/win/2.2/SafeExamBrowserInstaller.exe

**Comment by randy-knapp** [comment]
Thanks for getting back to me so quickly.

What I found out was that I was using a SEB Config file (.seb file) that was generated with the 2.1.3 version, but I was running the 2.1.8.1 version of the actual application.   That combination somehow caused the dialog to not display correctly.     When I recreated the config/seb file using the 2.1.8.1 Config tool and then ran with the 2.1.8.1 application, everything was fine.

I would assume what I did initially would not be “normal”.   Using a SEB file that wasn’t generated with the same version of the application.   So in my case, I don’t think it is/was a bug, but a mis-use of the tool.


Thanks
Randy

[http://emailsigs.breaktech.io/bt_logo.png]<http://www.breaktech.com/>

Randy Knapp
Managing Partner
D: 224.420.8102

Breakthrough Technologies LLC
General:847.864.0033
Visit us at breaktech.com<http://www.breaktech.com/>

[http://emailsigs.breaktech.io/linkedin_icon.png]<https://www.linkedin.com/company/breakthrough-technologies> [http://emailsigs.breaktech.io/twitter_icon.png] <https://twitter.com/break_tech>  [http://emailsigs.breaktech.io/facebook_icon.png] <https://www.facebook.com/Breakthrough-Technologies-282856188427598/>



Confidential information may be contained in this message. If you are not the addressee indicated in the message, you should destroy this message. @2017 Breakthrough Technologies, LLC.

[http://emailsigs.breaktech.io/fast50_logo.png]<http://www.chicagobusiness.com/section/fast-50-company?recipient=19>

[http://emailsigs.breaktech.io/codie_award_logo.png]<http://www.siia.net/codie/About-the-Awards/Past-Winners/2016-Finalists/Details/cID/90>

**Comment by dbuechel** [comment]
Hm. In theory, SEB files should be back- as well as forward-compatible. But we already had another problem with incompatibilities between versions 2.1.x and 2.2, since SEB 2.2 is quite different with a lot of new features. For now, I consider the issue solved, but do not hesitate to re-open it in case you encounter the problem again.

Cheers Damian
