### ISSUE TITLE
browserUserAgent only appends when browserUserAgentWinDesktopMode=1

### ISSUE THREAD

**Issue by trombonekenny** [SafeExamBrowser/seb-win#31]
### Description

Is the intention that `browserUserAgent` is appended to the user-agent header all the time, or only when a custom string is set?

Just adding the `browserUserAgent` string to my config didn't make the SEB 2.2 Windows client send it. I had to also set `browserUserAgentWinDesktopMode`=1 ... but then I lost the default user-agent string that SEB generated (because `browserUserAgentWinDesktopModeCustom` was blank).

I'm not sure if it's working as intended or a bug.

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: Windows 10 Pro
SEB-Version: 2.2 downloaded today from SourceForge

**Comment by danschlet** [comment]
Unfortunately there's a bug regarding the user agent in general in SEB 2.2. Only when the seb2 Firefox Profiles directory (in %APPDATA%\SafeExamBrowser\) is deleted, then the user agent is updated to the current settings. We have to fix this in SEB 2.2.1, we’re working already on it. 
browserUserAgent itself works according to my tests, as long as the Profiles directory is deleted, but that's not very helpful as long as the bug isn't fixed. There is the setting removeBrowserProfile which removes the Profiles directory when quitting SEB, don't know if that helps as a workaround in your case. But careful, this deletes all caches and local storage, IndexedDB etc.

**Comment by danschlet** [comment]
This issue was fixed in SEB 2.2.1.
