### ISSUE TITLE
Web pages dont load anymore

### ISSUE THREAD

**Issue by mokerhamer** [SafeExamBrowser/seb-win#33]
# Web pages dont load anymore

### Description

Download latest sources of 2.2.0, Compile, and install SEB (Used WIX installer). No edits at all. After installing client and launching SEB web page stays white.

### Environment & Version

Windows. SEB 2.2.0

- [ ] Mac
- [x] Windows

OS-Version: Windows 10 - 64 Bit
SEB-Version: 2.2.0

### Steps to Reproduce

1. Download latest 2.2.0 Sources.
2. Compile Sources.
3. Install Client (i used Wix installer)
4. Launch SEB, page stays white.

 Only 1 log file was generated, see attachment.
[SebClient.log](https://github.com/SafeExamBrowser/seb-win/files/1845443/SebClient.log)

Downloaded installer (V2.2.0) from the latest release works fine. am i doing somtehing wrong?

**Comment by mokerhamer** [comment]
I'm encountering this with the following branches, i cant find out what i am doing wrong:

- 2.2_ProcessWatching
- 2.2_merged
- 2.2.0

**Comment by dbuechel** [comment]
The WiX-Installer is incomplete and shouldn't be used. If the page still remains white after installing the official release, make sure to delete the `%APPDATA%\SafeExamBrowser` directory as well as all data under the installation directory.
