### ISSUE TITLE
SEB Config Tool not writing whitelistURLFilter correctly?

### ISSUE THREAD

**Issue by trombonekenny** [SafeExamBrowser/seb-win#35]
### Description

Is there a bug in the latest version of Windows SEB Config Tool with respect to writing the URL filters? If I set them, they don't seem to be saving ... XML file generated only shows the startURL filter being applied. If I save the config and reopen it, the Config Tool shows nothing in the Network tab.

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: Windows 10 Pro
SEB-Version: 2.2

### Steps to Reproduce

1. Run SEB Config Tool, save a new exam config file. Revert it to defaults and save.
2. Edit the Network tab to add a few filters. Save the file.
3. View the XML file and check what's in the whitelistURLFilter option

Am I missing something?

My goal is to learn about the regex format so I can reproduce it manually creating SEB files from our LMS, but I'm having troubles confirming the format under 2.2. Thanks in advance!

**Comment by dbuechel** [comment]
You are right, this appears to be a bug. Thanks for reporting it, we will address it in the upcoming release version 2.2.1.
To learn more about the filter rules (as they should work), you can refer to [https://safeexambrowser.org/windows/win_usermanual_en.html#NetworkPane](https://safeexambrowser.org/windows/win_usermanual_en.html#NetworkPane)

**Comment by danschlet** [comment]
Thanks for reporting this issue, it seems to happen when starting to edit a new file only. If you load an existing file and add the filter rules, they are saved.

Btw., are you aware that you only need to generate regex filter rules in special cases and if you want to generate config files compatible to SEB 2.1.x for Windows? SEB 2.2 uses the new URL filter rule format as mentioned in all [release](https://www.safeexambrowser.org/windows/win_release_notes_en.html) and [other notes](https://www.safeexambrowser.org/windows/win_usermanual_en.html#features) for the [new release](https://www.safeexambrowser.org/download_en.html).

SEB 2.2 for Windows (same as SEB for macOS) reads the new URL filter rule format (key _URLFilterRules_) and generates regex rules in the old format (keys _blacklistURLFilter_ and _whitelistURLFilter_), which the SEB for Windows browser uses and for compatibility to SEB 2.1.x for Windows. If you save your own filter rules only in the old keys _blacklistURLFilter_ and _whitelistURLFilter_, those will be overwritten by SEB 2.2 with rules it generates from the new key _URLFilterRules_. So you basically should only use the new key.

**Comment by trombonekenny** [comment]
Thanks for the bug confirmation and config tips. I'll focus on the `URLFilterRules` and let you know if I have any more problems or questions. Cheers!

**Comment by danschlet** [comment]
The [first preview version of SEB 2.2.1 is available now](https://github.com/SafeExamBrowser/seb-testing/tree/master/win/2.2.1), it contains some fixes in the URL filter, which should now be fully compatible between the Windows (2.2.1) and the Mac (2.1.3) version. I'll also provide a new preview version of SEB 2.1.3 for macOS with the same issue fixed in it.

**Comment by danschlet** [comment]
This issue was fixed in SEB 2.2.1 (final version was released).
