### ISSUE TITLE
QuitURL does not trigger on redirect

### ISSUE THREAD

**Issue by trombonekenny** [SafeExamBrowser/seb-win#36]
### Description

I'm noticing that a `quitURL` must be something clicked on by the user. Redirecting to the URL doesn't trigger the exit.

My intention in the LMS was to have the "Close assessment" form post redirect to the quitURL but it looks like an interim step is needed (redirecting to a page with the quitURL and instructions to click it).

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: Windows 10 Pro
SEB-Version: 2.2

### Steps to Reproduce

1. ~INSTRUCTION STEP 1~
2. ~INSTRUCTION STEP 2~
3. ~...~

> ***Information:** 
Please replace all placeholders (~PLACEHOLDER~) and version numbers according to your situation. The more detailed information you provide, the easier it will be for us to detect and reliably fix the issue. Feel free to delete this comment before submitting the issue report...*

**Comment by danschlet** [comment]
Are you sure about that? In the attached config file it works perfectly (Start URL https://safeexambrowser.org, Quit URL https://safeexambrowser.org/news_en.html, as the Start URL forwards to the second URL, SEB quits).

Make sure to use the correct quitURL: 

- There's an issue in SEB 2.2: A trailing slash is removed from the URL before comparing it with the quitURL, but if the quitURL also has a trailing slash, the comparison fails. We'll fix that in 2.2.1, a possible trailing slash in quitURL will also be removed. Until then, never add a trailing slash to quitURL.
- If your servers redirects https://example.com/exit to https://www.example.com/exit, you have to consider the www substring also in your quitURL

If it still doesn't work for you, then send us links and/or a config file, so we can reproduce it.
