### ISSUE TITLE
 x-safeexambrowser-requesthash

### ISSUE THREAD

**Issue by tzahiba** [SafeExamBrowser/seb-win#37]
# How is the x-safeexambrowser-requesthash calculated?

### Description
I am trying to understand how is the browserkey is being sent, and cannot find it.
After trying to change the textbox for my own key, it has failed to work.

- [ ] Mac
- [x] Windows

OS-Version: 10
SEB-Version: 2.2.1

**Comment by dbuechel** [comment]
You can find the specification here: https://safeexambrowser.org/developer/documents/SEB-Specification-BrowserExamKey.pdf

**Comment by tzahiba** [comment]
Hello dbuechel, is there no way to override that option, and just put my own key?
For my system specifications i would need a key which is up to 50 letters long.

**Comment by tzahiba** [comment]
If not, if there is any way u can help me locate the header adding in the code, since i could not find it on my own, thanks!
@dbuechel

**Comment by danschlet** [comment]
No, questions like this are out of the scope we can give support for here or in our SourceForge forum. If you need to discuss such development questions with the SEB developers, then your company/university or you need to become at least [Gold Member](https://safeexambrowser.org/consortium/fees.html) of the [SEB Consortium](https://safeexambrowser.org/consortium/members.html), then you get the right for direct contact and consultation with SEB developers.

You can try to contact us directly (info at safeexambrowser. org) and explain us your use case, maybe we can make an exception (for example if you're working on a non-commercial open source integration, but this need to be discussed first).

**Comment by tzahiba** [comment]
Alright, thank you
