### ISSUE TITLE
System (Win) variables do not work in application argument

### ISSUE THREAD

**Issue by twobaker** [SafeExamBrowser/seb-win#39]
### Description

If I add an argument with a Windows system variable to a permitted process in: SEB Config tool - Application pane: it doesn't work (could not open file, file not found).
**Configs**:
 Process: _acrord32.exe_
 Argument: _%homepath%\Desktop\document.pdf or C:\users\%username%\Desktop\document.pdf_

If I use _acrord32.exe %homepath%\Desktop\document.pdf_ it works perfectly

### Environment & Version

Windows standard
- [ ] Mac (not tested and of course different)
- [x] Windows

OS-Version: 10.1709\
SEB-Version: 2.1.3 (not tested with newer version, because this one is installed in our institution)

### Steps to Reproduce

1. In SEB Config add program e. g. acrord32.exe and an argument to %homepath%\Desktop\document.pdf (file have to exist)
2. Save config file and open SEB with it
3. Acrobat Reader will open with error message (file not found)
4. try same in CLI and it works _acrord32.exe %homepath%\Desktop\document.pdf_

It would be helpful for our setting. User can use own documentation for an exam and the easiest way is to palce a copy on their desktop.

**Comment by danschlet** [comment]
This feature was added to [SEB 2.2.1pre2 (preview 2)](https://github.com/SafeExamBrowser/seb-testing/tree/master/win/2.2.1). You can try this version out and let us know, if it works for you.

**Comment by twobaker** [comment]
I just tried SEB 2.2.1pre2. Everything works fine. Document  %homepath%\Desktop\document.pdf opened in SEB like it should.

Any idea when you will release a new SEB version with this feature? We will soon start renewing our builds for software distribution.

**Comment by danschlet** [comment]
SEB 2.2.1pre7 is the preview build solving all currently known issues which we just passed to our testing department. We might be able to release this in the next couple of months, but that depends on if they still find major issues or not. Otherwise it might be released only end of summer.
