### ISSUE TITLE
SSL Private/Server Certificate(s) with password protection.

### ISSUE THREAD

**Issue by mokerhamer** [SafeExamBrowser/seb-win#4]
Hello all,

This message is actually direct to @danschlet due to security reasons.
Can we get in touch? We're unable to get a certificate working on XUL runner, we can not relay details in public.

Skype: Mokerhamer (I just assume you're using Skype, )

Kind Regards

**Comment by danschlet** [comment]
Please write me an e-mail to daniel.schneider (at) let.ethz.ch.

**Comment by mokerhamer** [comment]
I have sended a e-mail yesterday. Have u received it? (daniel.schneider@let.ethz.ch)
