### ISSUE TITLE
[Question] Change the configuration during the exam

### ISSUE THREAD

**Issue by jp-weber** [SafeExamBrowser/seb-win#42]
### Description

Hello, I have a question regard to the change of the configuration during the exam. We using currently an own program, that use the exit key to close the SEB and load the new configuration from our server and start SEB again. I read that the exit keys will be removed in future versions. 

What is best way to change the configuration during the exam with a server request?

I see it exists a SEB server prototype. Will it be possible in the furutre to control the SEB clients with the server?
https://github.com/SafeExamBrowser/seb-server-prototype

### Environment & Version

Win7 & Win10

- [ ] Mac
- [x] Windows

SEB-Version: for 2.2(.X)

**Comment by danschlet** [comment]
Yes, in future you will be able to control SEB clients with the SEB Server. In addition we will introduce a JavaScript API which will amongst other functions allow to change the configuration during an exam.

In SEB 2.2.1 for Windows, you can configure an additional resource and embed a .seb config file. But this currently will only work to reconfigure SEB from client to exam settings (we should add the ability to change settings with this feature when already running an exam in an SEB update).

**Comment by saqib2st** [comment]
Hello! 
I'm using SEB 2.4.1 and trying to change the configuration but there is a configuration key & exam key but it's not enabled or ticked but if  I change the setting/configuration there also changing both of the keys is there any problem with my exam. if I change it.

**Comment by dbuechel** [comment]
Thanks for your report. SEB 2.x is no longer actively developed, we thus won't be able to solve this issue and highly recommend you using the latest version of SEB 3.x: https://github.com/SafeExamBrowser/seb-win-refactoring/releases. Should you encounter the same problem with SEB 3.x as well, please feel free to report it again under https://github.com/SafeExamBrowser/seb-win-refactoring/issues.
