### ISSUE TITLE
Windows Update 1803 causes Windows language switcher to appear on top of SEB fullscreen window

### ISSUE THREAD

**Issue by t00** [SafeExamBrowser/seb-win#44]
# Windows Update 1803 causes Windows language switcher to appear on top of SEB fullscreen window

### Description

After upgrade to Windows Version 1803 (build 17134.228) if there are multiple keyboards configured in the system and default Windows settings are kept, when Safe Exam Browser is launched in fullscreen mode (browserViewMode key set to 1), the OS keyboard switcher appears in the bottom right corner.

Option to hide SEB keyboard switcher (showInputLanguage) does not make any difference.

### Environment & Version

- [ ] Mac
- [x] Windows

OS-Version: 1803 build 17134.228 \
SEB-Version: 2.2

### Steps to Reproduce

1. Upgrade Windows to 1803
2. Start Safe Exam Browser

**Comment by dbuechel** [comment]
Thanks for your report. This is a known problem and appears to be a Windows bug. We have opened an issue report ([https://developercommunity.visualstudio.com/content/problem/288154/input-language-switch-appears-on-new-desktops.html](https://developercommunity.visualstudio.com/content/problem/288154/input-language-switch-appears-on-new-desktops.html)), but have not yet received any feedback. It seems however that Microsoft is aware of it, as the problem does not anymore happen in the current Insider Preview build of Windows 10. Thus, we unfortunately won't be able to do much about it for version 1803, unless someone happens to know a way to deactivate the language switch on new desktops (or Microsoft fixes the issue via Windows Update).

**Comment by dbuechel** [comment]
This issue will be fixed in the upcoming version 3.2, so we highly recommend updating SEB to version 3.x.
