### ISSUE TITLE
Windows pops up Firewall request

### ISSUE THREAD

**Issue by tzahiba** [SafeExamBrowser/seb-win#45]
#Windows pops up Firewall request
### Description
Hello, while trying to add my app to the allowed applications, windows has poped up this in the background
https://i.imgur.com/RKn2WFv.png
After this popued up I couldn't open the app in SEB.

### Environment & Version
lastest SEB
windows 7

- [x] Windows
OS-Version: 7
SEB-Version: 2.2

### Steps to Reproduce

Add a program which requires network output

**Comment by danschlet** [comment]
You have to configure Windows Firewall accordingly. I don't think we can or want to mess around with network settings. Especially when it's a **third party app which you add to permitted processes**, it's **your own responsibility** to make that app run correctly with **your Windows settings**. Allowed apps are anyways only recommended to be used in managed Windows accounts (managed PCs, VDI).

**Comment by tzahiba** [comment]
You are right, but why should the popup be poped behind the SEB and not inside?

**Comment by danschlet** [comment]
SEB has to hide message boxes and alerts, because the system or applications might display notifications or those popups might contain links to unwanted tools or similar. Unfortunately we can't selectively hide only some popups.
