### ISSUE TITLE
Windows Installer Silent

### ISSUE THREAD

**Issue by newboerg** [SafeExamBrowser/seb-win#47]
Windows Installer Silent

### Description

The Install shield Installer does not work correct when using "...exe /S /v /qn" (silent install)

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: X.X(.X) \
SEB-Version: 2.2.1

### Steps to Reproduce

run setup with "/S /v /qn" Flags.
Program should install without any dialogs.

Maybe you could switch to .MSI Packages for the Windows Release or look into the install Shield issue?

**Comment by dbuechel** [comment]
It appears that the last two parameters need to be concatenated: `SafeExamBrowserInstaller.exe /S /v/qn`. See e.g. http://helpnet.installshield.com/installshield19helplib/helplibrary/SilentInstall.htm.
