### ISSUE TITLE
Browser Exam Key does not work for Win 2.2.1 or 2.2.2pre1

### ISSUE THREAD

**Issue by danielx** [SafeExamBrowser/seb-win#48]
# Browser Exam Key does not work for win 2.2.1 or 2.2.2pre1

### Description

I can not get the Browser Exam Key to work in windows for version 2.2.1 or 2.2.2pre1

### Environment & Version

MSEdge on Win10 (x64) Stable (17.17134) for VirtualBox

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

- [ ] Mac
- [x] Windows

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

OS-Version: 1803 (17134.286)
SEB-Version: 2.2.1

### Steps to Reproduce

1. Start virtual machine from first snapshot
2. Install SafeExamBrowser 2.2.1
3. Reboot and wait for windows update
4. Set up a new request bin (https://requestbin.fullcontact.com/)
5. Open SEB Config tool
6. Edit settings
   - Start URL to the generated request bin
   - Allow in virtual machine
   - change use of SEB config file to: configuring an exam
   - Use Browser Exam Key
7. Save to file and extract BEK (8b48f8a181349a7c05cd7dac67c40ac17aaf14eafff08e3f6d3f8dce6e0e0798)
8. Double click config file
9. See the text OK for an ok Response
10. Check response in request bin inspector (https://pastebin.com/AkFiMiAf)
11. RequestHash could not be verified.

```
X-Safeexambrowser-Requesthash: 56601b1b8daf0b85ae2bfdf3f865c2373e33af47e5f35a4f74bf31da5530f13d
```

```python
>>> from hashlib import sha256
>>> h = sha256('http://requestbin.fullcontact.com/1eyzbkr1')
>>> h.update('8b48f8a181349a7c05cd7dac67c40ac17aaf14eafff08e3f6d3f8dce6e0e0798')
>>> h.hexdigest()
'920b062f7b4e13f14f94be24bc3e092fbbe286c7f9eec3eb4b17c66bafb7ba49'
```

**Comment by danschlet** [comment]
Are you aware that you need to [hash the Browser Exam Key with the URL](https://www.safeexambrowser.org/developer/documents/SEB-Specification-BrowserExamKey.pdf) of each request to compare it with the hash value the SEB browser sends in X-Safeexambrowser-Requesthash?

I recommend to look at the [Moodle implementation of the request header check](https://github.com/moodleou/moodle-quizaccess_safeexambrowser/blob/38bff93c2d3ab33969acf0c1429cdc7cdf3322f6/rule.php#L245). Every developer should be able to understand PHP more or less and in Moodle the check works perfectly.

**Comment by danschlet** [comment]
The other issue which unfortunately we can't do much about right now with the Browser Exam Key: A SEB for Windows client might create different hashes if an older SEB version was installed and that one is updated to 2.2.1/2.2.2pre1. This is the case if the older version left some files in the SebWindowsBrowser directory. If you have a case where you think the check doesn't work with one client, uninstall SEB with the Windows Control panel, delete its directory in Program Files (x86) and reinstall 2.2.1. I wouldn't use 2.2.2pre1 for now, as this is only a first preview.

**Comment by danielx** [comment]
Yes, i am aware and that is what the snippet of python code is doing. The Browser Exam Key check works fine for seb-win 2.2 and seb-osx 2.1.2 and 2.1.3 but not for seb-win 2.2.1

Well i tried version 2.2.1 from a fresh virtual machine that has never had SEB installed as explained in the steps to reproduce the issue.

**Comment by danschlet** [comment]
I found and fixed a bug in calculating the Browser Exam Key for specific config files. I'll add some more code to prevent the other issue when updating from an older SEB version and will release a SEB update (2.2.2) next week.

**Comment by danschlet** [comment]
I added a [preview version of SEB 2.2.2 (pre2)](https://github.com/SafeExamBrowser/seb-testing/tree/master/win/2.2.2) which fixes the Browser Exam Key issue mentioned before. It would be great if you could test that version and confirm that it works. 

I plan to release the final version of the 2.2.2 update with this fix asap, in the next couple of days.

**Comment by danielx** [comment]
When i went through the steps to reproduce again i found a (new?) issue.

It seems that when saving a config the computed BEK is incorrect. I could only get the correct BEK by re-loading the saved config file into the SEB Config Tool.

**Comment by danschlet** [comment]
Yes, you're right. I'll try to fix it properly tomorrow.

**Comment by danschlet** [comment]
Somehow I couldn't reproduce the error today, but I think I found more instances in the code where the wrong calculation could happen and fixed those.

Please test it with 2.2.2pre3.

**Comment by danielx** [comment]
I just tested with 2.2.2pre3 in a virtual machine and it worked with all the configuration options i tested it with.

Thanks! :smile:

**Comment by danschlet** [comment]
Ok, I'll make sure the new detector for additional files in the SEB browser directory (left over from not properly updated older versions) works correctly, do some re-testing and then release 2.2.2. Thanks for your feedback and testing!

**Comment by danschlet** [comment]
I fixed an issue in that new detector for additional files in the SEB browser directory. In my tests the key was also calculated correctly. I updated the version to 2.2.2 and consider this to be the Golden Master which I will release tomorrow, if no issues pop up until then anymore.
