### ISSUE TITLE
Support contract possible?

### ISSUE THREAD

**Issue by nicowitteman** [SafeExamBrowser/seb-win#49]
# Is it possible to sign a support contract for SEB?

### Description

We are considering using SEB for use in exams where up to 600 candidates can take the same test at the same time. Is there the possibility to have helpdesk-like support? Is such a construction offered? And can we be sure that SEB is staying to be supported in the years to come?

**Comment by danschlet** [comment]
No, we are no company and therefore cannot offer any support contracts. Maybe you can find a company which could provide helpdesk-like support. We are only offering support by the SEB developers for Gold and Principal Members of the [SEB Consortium](https://safeexambrowser.org/consortium/fees.html), but this is no helpdesk-support and only meant to support developers and system administrators in institutions which are implementing SEB support in their assessment solutions or environments.

The [SEB Consortium](https://safeexambrowser.org/consortium/members.html) is the body which sustains ongoing funding of the Safe Exam Browser open source project to continue its maintenance, development and support activities.
