### ISSUE TITLE
Calc.exe

### ISSUE THREAD

**Issue by nicowitteman** [SafeExamBrowser/seb-win#54]
# Win 10 calculator starts outside SEB

### Description

Under Windows 10, the calculator app added as a permitted application will not start within SEB, but only become visible after closing SEB.

### Environment & Version
Desktop PC

- [ ] Mac
- [x] Windows

OS-Version: 10
SEB-Version: 2.2.2

### Steps to Reproduce

1. In config tool, add c:\windows\system32\calc.exe to applications/permitted processes
2. Start SEB using this configuration
3. From the task bar, click on the calculator icon
4. Nothing appears to happen
5. Quit SEB
6. Notice the active calculator

(I think this issue was submitted before, but closed without comment)

**Comment by danschlet** [comment]
https://sourceforge.net/p/seb/discussion/844844/thread/65edcecd/

Unfortunately there is no way that UWP apps can be run as third party applications during exams (in a kiosk mode) unless Microsoft doesn’t provide such a functionality in the Windows API (the calculator in Windows 10 is an UWP app). If you need a calculator, you will have to look for an alternative calculator application which isn't a UWP app and add it as an permitted process.
