### ISSUE TITLE
SEB Touchscreen unter Windows 10 mit Virtual Keyboard

### ISSUE THREAD

**Issue by hulky123** [SafeExamBrowser/seb-win#55]
Virtual Keyboard geht nicht unter Windows 10 auf. (Im SEB Modus)

### Description

Wir starten im SEB eine URL (Web) und möchten gerne das Virtual Keyboard von Windows 10 einblenden lassen.
Leider macht SEB in keinster weise dieses Keyboard auf. In den Einstellungen habe ich alle erdenklichen Variationen ausprobiert. Touch Modus auf an & aus.
Wie könnte ich das Virtuelle Keybooard beim drücken in ein Eingabefeld in einer Webpage einblenden lassen?

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: Windows 10 pro
SEB-Version: 2.2(.2)

**Comment by dbuechel** [comment]
Vielen Dank für die Meldung. Es scheint tatsächlich so zu sein, dass sich das Keyboard gar nicht mehr öffnen lässt ab Version 1803. Wir werden das Problem frühestens mit der nächsten Version beheben können.

**Comment by hulky123** [comment]
Wann können wir mit dem nächsten Release rechnen?

**Comment by danschlet** [comment]
Eine Lösung für das Problem mit dem On-Screen-Keyboard wird längere Zeit in Anspruch nehmen. Momentan kann SEB unter Windows 10 deswegen im Touch/Tablet-Modus nur mit externen Tastaturen betrieben werden. 

Für Anwendungen, wo echte Tablets notwendig sind, empfehle ich iPads einzusetzen. Die nächste SEB-Version für iOS (Release noch im November) wird praktisch alle Features der Desktop-Versionen nachreichen (Browser Exam Key und Config Key, URL-Filter, Zertifikatsverschlüsselung). Im Gegensatz zu SEB für Windows ist bei iOS die Unterstützung von On-Screen-Keyboard u.ä. über das Betriebssystem geregelt und muss nicht emuliert werden wie in der gegenwärtigen Windows-Version.

**Comment by dbuechel** [comment]
Das Problem liegt daran, dass Microsoft das OSK in eine UWP-App verwandelt hat. Glücklicherweise scheint es einen Registry-Key (Typ `DWORD`) zu geben, welcher die alte Implementation reaktiviert:

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\TabletTip\1.7\DisableNewKeyboardExperience`
•	`0` = neue Implementation (UWP-App)
•	`1` = alte Implementation

Für 64-Bit-Maschinen muss derselbe Key auch unter `HKEY_CURRENT_USER` gesetzt werden. Danach PC neu starten und Tablet-Modus aktivieren, dann sollte das OSK wieder funktionieren (jedoch nur im Kiosk-Modus "Disable Explorer Shell").
