### ISSUE TITLE
Red lock screen appears. Unclear what the reason is

### ISSUE THREAD

**Issue by ramonavic** [SafeExamBrowser/seb-win#56]
# Red lock screen appears on launch

### Description

Dear SEB,

First of all, we use SEB on various schools and get a lot of positive feedback on your application. 

On one of our schools there seems to be a uniform problem where on startup SEB shows the red lock screen implemented in the 2.2.1 release. 
This happened to about 80% in a group with the same devices and only on the startup of the SEB client. 
After entering the lock password most students said they were able to continue in an "unconnected"
state (show in red in the upper left of the browser).

We have recovered two log files from the school in question but can't see any lead to what may have triggered this lock state. 
Would you be able to explain why this occurs and what we can do against it? 

[SebClient (3).log](https://github.com/SafeExamBrowser/seb-win/files/2556887/SebClient.3.log)
[SebClient (2).log](https://github.com/SafeExamBrowser/seb-win/files/2556888/SebClient.2.log)

### Environment & Version

- [ ] Mac
- [x] Windows

OS-Version: 10
SEB-Version: 2.2.6817.21388

**Comment by dbuechel** [comment]
Thanks for your report. The lock screen is rendered by the (independently running) browser engine when it looses the connection to the main SEB component. The two applications communicate with one another via a WebSocket connection on the local host. The exact reason why the lock screen is rendered should be logged in the browser engine log (written to file `seb.log`). "Unconnected" means that the connection to the main SEB process could not be restored, hence multiple features of SEB (like Additional Resources) won't work as long as SEB remains in that state.
A possible reason for the problem could be proxy or other related network settings or strict anti-virus software which interferes with the WebSocket communication. I recommend checking the system event logs for any suspicious entries as well as reviewing the system configuration with regard to the above mentioned inner workings of SEB.

**Comment by ramonavic** [comment]
@dbuechel and @danschlet, a big thank you for your timely and helping replies. 
It sounds likely that the current proxy settings are blocking the socket service. 
I will contact the school about this and suggest whitelisting localhost. 
When I hear from them I will report back.

**Comment by jduminy** [comment]
@ramonavic did you ever resolve this? We are experiencing exactly the same issue.

**Comment by ramonavic** [comment]
@jduminy in the end we didn't solve this but the system admin of the related school did. They made a proxy exception for our domain and made a hole in their firewall for our application IP. Hopefully this helps, good luck!
