### ISSUE TITLE
Autostart does not affect main exam

### ISSUE THREAD

**Issue by tzahiba** [SafeExamBrowser/seb-win#64]
# Autostart does not affect main exam

### Description

Autostart does not affect main exam, meanin if I try to change its status from AutoStart active to nonactive, it still opens up when the SEB starts up

### Environment & Version

- [x] Windows

OS-Version: 10 1809
SEB-Version: 2.2

### Steps to Reproduce

1. Open SEB Config Tool
2. Set firefox.exe as non Autostart
3. Open it up and see it auto starts.

Thank you

**Comment by danschlet** [comment]
The built-in Firefox is always autostartend, most of the settings for the built-in Firefox in Permitted Processes are ignored (you can add command line arguments for starting the Firefox though.

If you want to use SEB without the built-in Firefox (to only start third party applications defined in permitted processes), then use the setting [Use SEB without browser window](https://safeexambrowser.org/windows/win_usermanual_en.html#BrowserPane).
