### ISSUE TITLE
Custom Login password in SEB Config Tool is not working

### ISSUE THREAD

**Issue by suthishan** [SafeExamBrowser/seb-win#67]
# Custom Login password in SEB Config Tool is not working

### In SEBSettings.cs  file , manually i have changed the password in	SEBSettings.settingsDefault.Add(SEBSettings.KeyHashedQuitPassword , "password@123"); but while executing the file to exe. custom password which i have set in that file is not working. it shows wrong password. 

What was the issue, how can i rectify this issue.

please view the screenshot below.

![screenshot 6](https://user-images.githubusercontent.com/32566422/52847728-fc263900-3132-11e9-9714-0ba3e4d21698.png)

![screenshot 7](https://user-images.githubusercontent.com/32566422/52848043-ccc3fc00-3133-11e9-8565-ac5e76333ec5.png)

**Comment by dbuechel** [comment]
There is no login password in SEB. You can configure an administrator, a settings and a quit password, as described in the documentation: [https://safeexambrowser.org/windows/win_usermanual_en.html#GeneralPane](https://safeexambrowser.org/windows/win_usermanual_en.html#GeneralPane).

Furthermore, you'll need to set the hash value of said passwords in the raw configuration data, not the plain text password.
