### ISSUE TITLE
SpeechSynthesis support?

### ISSUE THREAD

**Issue by wboebel** [SafeExamBrowser/seb-win#68]
It does not appear that the SpeechSynthesis API is working in the Safe Exam Browser.  It has been supported in Firefox since v49.  I believe you are using Firefox v52 for Safe Exam Browser Windows 2.2.2.

Any advice on how to get it working?

Error is "SpeechSynthesisUtterance is not defined" when trying to instantiate and instance.

API reference: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis

**Comment by wboebel** [comment]
Also, I did launch the Firefox.exe instance (v52) that is inside the xulrunner folder and the speech synthesis works fine there, just not in Safe Exam Browser.

**Comment by danschlet** [comment]
Check out the [preview version of SEB 2.3](https://github.com/SafeExamBrowser/seb-testing/tree/master/win/2.3). We activated the SpeechSynthesis API there, please test if it works for you and let us know.

**Comment by wboebel** [comment]
It does seem to be working.  We will test further.  Thank you!

When do you expect v2.3 will be released as a stable version and not a preview release?

**Comment by danschlet** [comment]
SEB 2.x is now legacy software, try it in SEB 3.x with its more modern Chromium browser engine.
