### ISSUE TITLE
Extend change of Registry Keys

### ISSUE THREAD

**Issue by Eulender** [SafeExamBrowser/seb-win#7]
Is it possible to extend the changeing of registry keys? We need to hide some drives.
Now we have made a batch script to change the registry keys before starting seb and change it back after closing the tool. It would be fine if we could do this in the configuration tool. 

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoViewOnDrive
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\nodrives 

With this keys enabled the users have no possiblilitys to start or open files from the local disks in third party applications.

Tia
Christoph Eder

**Comment by danschlet** [comment]
Are you sure that users cannot start and open files from those drives? As far as I know, this Registry key just hides drives, users still can access it by entering the path manually in a file open dialogue.

**Comment by mokerhamer** [comment]
Add your own registery edits to the sources. a good example is the keyboard coding.

Example:
`public static bool IsKeyboardDocked()
        {
            int docked = 1;

            try
            {
                //HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7\EdgeTargetDockedState -> 0 = floating, 1 = docked
                docked = (int)Registry.GetValue(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7\", "EdgeTargetDockedState", 1);
            }
            catch { }

            return docked == 1;

        }`

**Comment by pawy** [comment]
Hi

Well, it is possible to restrict access to a specific drive. The point is that you cannot remove access to the drive where seb is running on and that means there is still a drive accessible. The feature then is a bit dangerous to configure if you can enter a drive letter to which the access is restricted you may create a lot of damage on a computer that uses different drive letters.

**Comment by Eulender** [comment]
Hi, ok this keys are like security by obscurity but, in kombination with a little autoit script to hide the adressbar (controlhide("","","ToolbarWindow") in the open dialogs, and hide the favorites and network links in explorer (wengpcfg). Then there is no simple way to open any other programm or file.

**Comment by mokerhamer** [comment]
Post a tutorial about how you sholved it. i might add a registery manager.

Already added the following:
*Wiz installer (From 2.2 Merged Sources)
*SEB Server - SEB Clients pickup .seb configuration from server at startup.
*Word / Excel secured - Disabled all sharing options.
*Eqsoft Certificate manager (Reads user profiles cert8.db and key3.db that stores all firefox certificates used by SEB)
*Working on a PDF Viewer (External links) - In progress.

**Comment by Eulender** [comment]
Today there are 3 Programms in use
- One ist the SEB Browser with its service
- The next one is a selfwriten service which is waiting in th background for the safe exam browser prozess. If the prozess starts it changes the registry keys for to hide the unwanted drives.
Because of the design of the seb browser the registry keys are reloded and so we need no relogin or restart to take effect of the changed keys. After the sebclent starts a programm which runs in the background. This programm is waiting for the typical explorer open dialog. If the dialog is visible it disables the address toolbar so there is no possibility to start a not authorised programm from the toolbar.
This Programm is also able to capture the screen and save the screenshots every 10 or 20 seconds.
After the exam the service rebuild the origninal registry keys. 

Example open/save dialog --> only german version (writen in autoit script language)

While 1
	if WinWaitActive("Öffnen","",1)>0 then
		controldisable("","","ToolbarWindow321")
		controldisable("","","ToolbarWindow322")
		controldisable("","","ToolbarWindow323")
		controldisable("","","ToolbarWindow324")
	endif

	if WinWaitActive("Speichern unter","",1)>0 then
		controldisable("","","ToolbarWindow321")
		controldisable("","","ToolbarWindow322")
		controldisable("","","ToolbarWindow323")
		controldisable("","","ToolbarWindow324")
endif
wend

**Comment by Eulender** [comment]
sorry i didnt want to close this issue. :)

**Comment by danschlet** [comment]
All of this sounds interesting, but I don't think it's something we could built into the general release of SEB. It might work in a managed, well known environment, but I think it is too risky in BYOD exams, as systems and installed third party applications can be very diverse and if something goes wrong with resetting registry settings on student owned devices they will be very unhappy.

And are you doing something about built-in help browsers (unfortunately available in many applications)? You would need to filter system-wide internet access.

We prefer to do all exams using third party applications in a virtual desktop environment, with the client exam computer being secured by SEB. In the virtual desktop we have much more control over the exam environment. 

[German info page about SEB and VDI](http://safeexambrowser.org/vdi/)
[English technical description of the environment](http://safeexambrowser.org/vdi/Competence-Oriented_Exams_VDI+SEB_ETH-LET_2013_07.pdf)
