### ISSUE TITLE
Full screen mode with auto hide Windows task bar clips bottom content

### ISSUE THREAD

**Issue by danielx** [SafeExamBrowser/seb-win#71]
**Describe the Bug**
If the user has set the Windows task bar to auto hide (or vertical) and the configuration specifies that the browser view mode should "Use full screen mode" the bottom SEB-taskbar clips some content on the bottom of the page.

**Steps to Reproduce**
1. Set Windows task bar to auto hide (or have it docked to the left/right)
2. Set config to "Use full screen" under browser view mode in the User interface section.
3. Content at the bottom is hidden behind the SafeExamBrowser task bar

**Expected Behavior**
The page should still be full screen and not have some content hidden behind the task bar

**Screenshots**
Note that the scroll bar gets hidden behind the SEB task bar.
https://i.imgur.com/1nEio2g.png

**Version Information**
 - OS: Win 7, Win 10
 - SEB-Version 2.2.3

**Comment by danschlet** [comment]
This is a known issue in SEB 2.x. It is fixed in SEB 3.0, but as fixing it in SEB 2.x would take too much time, we won't fix it in version 2.x.
