### ISSUE TITLE
not working properly under Windows auth on Active Directory

### ISSUE THREAD

**Issue by jpahullo** [SafeExamBrowser/seb-win#72]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**

We have tried out SEB under several Windows workstations. We found that those workstations configured to authenticate locally, SEB works ok and as expected. 

On the contrary, using SEB on a Windows workstation with centralized authentication up to an Active Directory, SEB does not work as expected: we don't see the bottom toolbar with all those options. We only see a white rectangle on what it should be the toolbar.

**Steps to Reproduce**
1. Setup SEB on a Windows workstation with Active Directory centralized authentication.
2. Open the SEB config and update the URL of the Moodle LMS.
3. Open SEB. 
4. At this stage, we can see the Moodle LMS, but not the toolbar. Being at this point, you can only hard reset the workstation pressing the power button.

**Expected Behavior**
See the SEB toolbar work as expected.

**Version Information**
TODO

**Additional Context**
Not any particular

**Comment by dbuechel** [comment]
If I understand you correctly, you are using the default settings and only changing the Start URL? If yes, we'd need the log files to further investigate the issue. Did you try to quit with CTRL+Q when SEB hangs? Also, which SEB version are you using?

**Comment by jpahullo** [comment]
Good to know. We will provide the details you asked for in short.

Thanks in advance!

**Comment by danschlet** [comment]
Closed for now, as no feedback was given.
