### ISSUE TITLE
LAb Computer

### ISSUE THREAD

**Issue by yakarsu** [SafeExamBrowser/seb-win#76]
Hello

I installed SEB 2.3 we are using SEB in LAB but When different users log on to computers, each user needs setting. How we can solve this issue?

# ~ISSUE TITLE HERE~

**IMPORTANT**
Please _always_ consult the documentation first before creating an issue!
https://safeexambrowser.org/windows/win_usermanual_en.html

### Description

~YOUR ISSUE DESCRIPTION HERE...~

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: X.X(.X) \
SEB-Version: X.X(.X)

### Steps to Reproduce

1. ~INSTRUCTION STEP 1~
2. ~INSTRUCTION STEP 2~
3. ~...~

> ***Information:** 
Please replace all placeholders (~PLACEHOLDER~) and version numbers according to your situation. The more detailed information you provide, the easier it will be for us to detect and reliably fix the issue. Feel free to delete this comment before submitting the issue report...*

**Comment by dbuechel** [comment]
As is explained in the [documentation](https://safeexambrowser.org/windows/win_usermanual_en.html#ConfigFilePane), you can place a configuration file for all user in ``%PROGRAMDATA%\SafeExamBrowser``.
