### ISSUE TITLE
[Question] set browser preferences

### ISSUE THREAD

**Issue by victorcatn** [SafeExamBrowser/seb-win#77]
# [Question] set browser preferences

### Description

I want to set a preference for the firefox browser (security.mixed_content.block_active_content, false) I want to know if it is possible and how. Thank you.

### Environment & Version

- [ ] Mac
- [x] Windows

OS-Version: 10 \
SEB-Version: 2.2.3

**Comment by danschlet** [comment]
As SEB 2.x using the outdated, not updatable Firefox 52ESR browser engine (because Mozilla doesn't support the XULRunner technology anymore), we won't add this feature to this legacy SEB version anymore. Try to use SEB 3.x with its Chromium browser engine.
