### ISSUE TITLE
SEB Windows service is stopped or the installed SEB got corrupted in Windows 10 + SEB2.3

### ISSUE THREAD

**Issue by leewtai** [SafeExamBrowser/seb-win#79]
NOTE: This is a duplicate of the one on SourceForge: https://sourceforge.net/p/seb/bugs/98/

**Describe the Bug**
I have 2 students, both with Windows 10, both with SEB 2.3, using a configuration file I created in the MacOS SEB (v2.1.3). 
Both are getting the same error after entering the setting password.
"SEB Windows service is stopped or the installed SEB got corrupted. Rebooting your machine or reinstalling SEB might help. Inform your exam adminisrtator/supporter. The exam cannot be started. SEB will quit now."
Student B claimed to have rebooted their computer and reinstalled SEB. However, student B was also able to launch SEB without using the configuration file BUT they said the same error message did appear before the default screen appeared (the non-configured SEB screen).
Many other students are not having this issue.

Below are the logs from student A
[seb.log](https://github.com/SafeExamBrowser/seb-win/files/3690975/seb.log)
[SebClient.log](https://github.com/SafeExamBrowser/seb-win/files/3690976/SebClient.log)

**Steps to Reproduce**
The config file is here:
https://drive.google.com/open?id=13sT0ZxeJooJpkdiaBSxJMP2r6jQKgl7V
setting pwd: 'hello'
quitting pwd: 'quit'
admin pwd: 'simplestat'

Downloaded SEB2.3 from SourceForge and clicking on the config file. 
Then after entering the setting pwd, the following image appears:
![1](https://user-images.githubusercontent.com/50937091/66216563-b2736a00-e693-11e9-851c-f5258c41dbba.jpg)

**Expected Behavior**
I'm expecting the starturl  "us.edstem.org" to appear.

**Version Information**
 - OS: Windows 10
 - SEB-Version 2.3

**Comment by danschlet** [comment]
SEB Windows Service can get stopped by some anti-malware software (or security policies on that machine) which [falsely identify SEB as malware](https://safeexambrowser.org/faq/faq_en.html#Windows). You can try to add SEB as "allowed" software in the settings of that anti-malware software or deactivate/uninstall that software before running the exam with SEB. Also SEB 3.0.1 by default doesn't use the SEB Windows Service (this is configurable though), and might not have that issue anymore.
