### ISSUE TITLE
Win32 calculator calculates wrong values [Win10 1809 LTSC]

### ISSUE THREAD

**Issue by jp-weber** [SafeExamBrowser/seb-win#80]
**Describe the Bug**
The classic calculator calculates wrong values with active SEB, for example sqrt(9). Without SEB, the calculator works normal.

Also noticed that when the calculator mode is set to programming, the calculator crashes inside the SEB.

**Steps to Reproduce**
1. Win10 1809 LTSC with win32calculator.exe
2. for example calc sqrt(9) or log(10)
3. See wrong values

**Expected Behavior**
The calculator should work like without the SEB.

**Version Information**
 - OS: Windows 10 Enterprise LTSC, Version 1809
 - SEB-Version 2.1.3. and 2.3

**Additional Context**
With the Win10 1607 LTSB it works like it should.

**Comment by danschlet** [comment]
Probably the classic calculator isn't compatible to the kiosk (lockdown) mode SEB has to use to secure the PC. You will probably need to use another calculator application, this doesn't seem like a problem we can solve in SEB.
