### ISSUE TITLE
SEB bottom-bar does not show properly

### ISSUE THREAD

**Issue by a-camacho** [SafeExamBrowser/seb-win#83]
**Describe the Bug**
When starting SEB on a Windows VDI, the SEB bottom-bar (with SEB logo, ressources and third party apps) sometimes show in a wrong place on the screen. Instead of sticking to the bottom of the screen, we observed two "places" where the bar goes sometimes :

1. The bar shows at the top of screen
2. The bar shows at the bottom of screen (but a margin/padding of 40px is there, the margin/padding seem to have the same height as SEB bottom bar) 

**Steps to Reproduce**
1. Start exam automatically after VDI startup on multiple machines
2. We see this behaviour on 0-15% machines. We didn't have this behaviour before using 2.3.

**Expected Behavior**
SEB bottom-bar should always stick at the bottom of the screen.

**Screenshots**
_Example of the bar at bottom **but with margin/padding**_

![image1](https://user-images.githubusercontent.com/29976133/72334942-6edec200-36be-11ea-8a08-83097f0449c2.jpeg)
![image0](https://user-images.githubusercontent.com/29976133/72334954-72724900-36be-11ea-9189-c3e4c888cd83.jpeg)

**Version Information**
 - OS: Windows 10 LTSC 2019, Version 1809
 - SEB-Version : 2.3

**Additional Context**
We are starting SEB automatically at machine startup. Delaying exam start does not solve the problem. Strangely, on one of our VDI pools (so, on our master image) this bug does not occur. We are not being able to understand the difference between this master image, and the others (they should be exactly the same).

Another important information : when SEB is started, the VDI resolution is already set up and Windows environement actually takes all screen space.

**Comment by dbuechel** [comment]
Just to clarify: You did not change the SEB version, i.e. things were working fine with SEB 2.3 but then stopped working at some point in time?

**Comment by a-camacho** [comment]
We did not have any problem regarding this issue with the previous version (windows 2.2.3).
So we started having this problem when we started using the new version (windows 2.3).

What is strange, is that this problem does not happen on all our exams. One master image (that is almost exactly to others) does not cause this issue (even if SEB version, Windows version, startup script, everything* is the same).

**Comment by dbuechel** [comment]
As far as I know, we did not change anything related to the taskbar position or layout between those two versions. Are you absolutely positive that the issue originates from SEB, i.e. are you using the same Windows version, VDI version etc.?

**Comment by dbuechel** [comment]
And did you check the log files of the affected computers at the time the problem happened?

**Comment by a-camacho** [comment]
> As far as I know, we did not change anything related to the taskbar position or layout between those two versions. Are you absolutely positive that the issue originates from SEB, i.e. are you using the same Windows version, VDI version etc.?

No, I'm not sure that the problem originates from SEB but I was asking if you had any idea of something that could cause this trouble.

FYI : If sometimes the SEB sticks to the top of the screen, the only other position is at the bottom of the screen with a padding that is exactly of the size of the SEB bar. That made us think that SEB could be the issue or at least participate to it.

> And did you check the log files of the affected computers at the time the problem happened?

Were you talking about SEB logs ? We didn't see anything in it, but maybe we could provide you with it.

**Comment by dbuechel** [comment]
That the SEB taskbar would appear at the top of the screen is inexplicable to me. I have only seen the second scenario you mentioned, where the taskbar is shifted upwards by roughly its own height. But this in a different situation, namely when the Windows shell (explorer.exe) was started while SEB was running. Then it seems to be the case that the Windows shell will move any obscuring windows out of the way to be able to place its own taskbar at the bottom of the screen.

> Were you talking about SEB logs ? We didn't see anything in it, but maybe we could provide you with it.

Yes exactly. If the Windows Explorer indeed was started, then you should find that information there.

**Comment by danschlet** [comment]
We consider this a non-blocking issue and won't investigate a fix for SEB 2.x anymore. If you observe the same issue in SEB 3.0, we will investigate and fix it for SEB 3.x.
