### ISSUE TITLE
SEB 2.4 for Windows - timetable

### ISSUE THREAD

**Issue by marjutanderson** [SafeExamBrowser/seb-win#85]
Hi,
we are developing our own assessment system for Finnish universities and last year we decided to check how SEB would work with our system. First technical implementation is based on Config Key feature and everything works well with macOS. Do you have any estimation when SEB 2.4 for Windows (Config Key feature) would be released for testing, looks like the plan was earlier in the end of 2019 but now estimated for Q1?
Br, Marjut Anderson

**Comment by danschlet** [comment]
We are working on SEB 2.4, a preview version for testing should be available in the next two weeks. Depending on our testing capacity, the final release might happen slightly later than until end of March.

You can already test the Config Key with the completely refactored version SEB 3.0 for Windows (which is using a new, Chromium-based browser engine). This development of this version is almost finished, first testing just started. You can find the automated builds via the GitHub repository, see https://github.com/SafeExamBrowser/seb-win-refactoring. SEB 3.x comes in x86 and x64 builds, thus you’ll either need to navigate to the respective platform on the build server, or simply use the setup bundle (which automatically installs the correct build for a platform, including all required dependencies like the .NET framework and C++ runtime). The setup bundle can be found under the x86 platform build, see screen shots.
![image001](https://user-images.githubusercontent.com/2464749/75997500-b4ba4880-5eff-11ea-8be8-2c9f5a81c71e.png)
![image002](https://user-images.githubusercontent.com/2464749/75997507-b7b53900-5eff-11ea-9b8a-fe70daf85abf.png)

**Comment by danschlet** [comment]
SEB 2.4 and [SEB 2.4.1](https://safeexambrowser.org/download_en.html#WindowsLegacy) which both support the Config Key (same as SEB 3.0.1) were now released.
