### ISSUE TITLE
Environment Variables Expansion for permitted paths

### ISSUE THREAD

**Issue by liuq** [SafeExamBrowser/seb-win#88]
**Is your feature request related to a problem? Please describe.**

Currently, permitted applications that are not installed in the system path must be specified with a full path, but for some of them (those installed in AppData, such as Zoom, Microsoft Teams, Webex and similar) the path changes according to the user who installed them.

However, the path could be specified using environment variables (such as %AppData% or %USERPROFILE%) that would allow to identify exactly that application that has permitted access.

**Describe the solution you'd like**

I already patched the current code (2.2_merged branch) with the two lines of code that will allow environment variable expansion as last resort in determining the full path and issued a pull request for that.

Please urgently merge them in a minor release of the tool. The world needs it! ;-)

**Describe alternatives you've considered**

Unfortunately other alternatives, such as writing a web app for proctoring would be extremely more time consuming. 

**Additional context**

**Comment by danschlet** [comment]
[SEB 2.4.1](https://safeexambrowser.org/download_en.html#WindowsLegacy) which should fix this issue was now released.
