### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ahmedali19** [SafeExamBrowser/seb-win#90]
The feature you are trying to use is on a network resource that is unavailable
 I receive this error when I try to install safe exam browser on windows 7. Please help. Error screenshot is attached
![Error](https://user-images.githubusercontent.com/48640271/80279097-c4daf100-8714-11ea-9e90-e7ccf1614a99.png)

**Comment by dbuechel** [comment]
I doubt that this is an error in the SEB installer. It appears to me that you're having network issues, I would advise that you contact your system administrator first. We can reopen the issue if it indeed has something to do with the SEB installer.
