### ISSUE TITLE
SEB Failed to completely lockdown the computer

### ISSUE THREAD

**Issue by yxy0725** [SafeExamBrowser/seb-win#91]
I installed the latest version of SEB, once I try to open it, it shows "Failed to completely lockdown the computer". Please help me out!!!! Thank you.
![Service Error](https://user-images.githubusercontent.com/65840021/82744861-3d949380-9d3b-11ea-9e4d-156ec53c5e81.jpg)

**Comment by dbuechel** [comment]
This is a known issue and will be fixed with the an update, namely version 2.4.1

**Comment by danschlet** [comment]
[SEB 2.4.1](https://safeexambrowser.org/download_en.html#WindowsLegacy) which should fix this issue was now released.
