### ISSUE TITLE
Can't write letter p

### ISSUE THREAD

**Issue by zezao28** [SafeExamBrowser/seb-win#94]
I am a student using the SEB version 2.4 for windows 10 home. When I'm using the SEB to make an exam I can't write the letter P. Every other works well and outside of SEB it also works fine, so its not a hardware problem. Does someone know how to solve this?

**Comment by dbuechel** [comment]
Where are you trying to write the letter p? Can you provide a step-by-step instruction (including the web site / third-party application / etc. you're using)?

**Comment by zezao28** [comment]
Hello, I can't type it anywhere as long as I'm using the seb browser.
Here's a step by step of what I do:
1. I open my seb file, which opens seb browser and redirects to moodle.utad.pt
2. There I have to log in to my account to make the exam
3. My username and password don't have a p in them but I can't type it in this boxes too
4. When I try to answer a question or type anything, it doesn't let me use the letter p

**Comment by dbuechel** [comment]
I'm afraid I can't reproduce the issue. I am able to enter the letter "p" on the website you mentioned. Did you try using a different start URL (e.g. https://www.duckduckgo.com) to see whether you're able to type the letter "p" there?

**Comment by dbuechel** [comment]
Thanks for your report. SEB 2.x is no longer actively developed, we thus won't be able to solve this issue and highly recommend you using the latest version of SEB 3.x: https://github.com/SafeExamBrowser/seb-win-refactoring/releases. Should you encounter the same problem with SEB 3.x as well, please feel free to report it again under https://github.com/SafeExamBrowser/seb-win-refactoring/issues.
