### ISSUE TITLE
Black screen on my Win7 after SEB launching

### ISSUE THREAD

**Issue by stockiNail** [SafeExamBrowser/seb-win#97]
**Describe the Bug**
I have installed SEB 2.4 on my laptop with Windows 7 and I have launched it. Unfortunately my screen is now completely black and I can not do anything. 
I can not switch off my laptop and restart my Win7 because it goes in standby.
 
**Expected Behavior**
My expectation was to have the browser.

**Screenshots**
Screen completely black.

**Version Information**
 - OS: Window 7
 - SEB-Version 2.4

**Comment by danschlet** [comment]
Sorry to hear that you are having these kinds of issues. 

You need to find out how to perform a hardware (forced) shutdown of your laptop. Every computer should has a force shutdown or force reset function, but sometimes some special button or keyboard shortcut has to be used (not the regular reset or shutdown shortcut). If your laptop has a removable battery, then removing it, waiting shortly and putting it back in while connecting to an external power source should reboot the computer fully. SEB does not interfere in the boot process and doesn't autostart after a reboot. 

Probably setting the Registry power options failed, either this will be restored automatically after rebooting or you can use the SEB Registry Resetter tool (see https://safeexambrowser.org/windows/win_usermanual_en.html#RegistryPane) to get those Registry settings back to its normal state.

Probably some anti-malware software blocked SEB from working correctly, we had such cases reported (although no one ever reported that a computer couldn't be restarted anymore). Deactivating or uninstalling incompatible anit-malware software before running SEB 2.4 or using SEB 3.0.1 (which doesn't change the Registry Settings anymore) should solve these issues.

**Comment by stockiNail** [comment]
Reported into SF https://sourceforge.net/p/seb/bugs/120/
