### ISSUE TITLE
Config Key not working

### ISSUE THREAD

**Issue by luisamveloso** [SafeExamBrowser/seb-win#98]
Hello,

I am a teacher in a Computer Science BSc. I did read the manual and tested several times by myself, with colleagues and students. At my institution (Polytechnic Institute of Coimbra) we would like to use the "Config Key" since it doesn't change with the SEB version. However, after copying this key into the moodle exam configuration, this LMS does not allow to perform the exam even when using the correct SEB file (from which the key was copied). 

**Describe the Bug**
After copying the "Config Key" into the moodle exam configuration,  this LMS does not allow to perform the exam even when using the correct SEB file (from which the key was copied). 

**Steps to Reproduce**
1. Generate the SEB file;
2. Copy the Config Key from the SEB file to the moodle exam configuration;
3. When trying to use the SEB client file to perform the exam, the moodle informs that we are not using the correct SEB file. However, when doing the exact same thing with the "Browser Exam Key" the exam can be performed without problem. I do not know if the problem resides in the server or in the client. I tried with both the 2.4 and 3.0.1 versions of the SEB client, but obtained the same exact results.

**Expected Behavior**
Allowed to perform an exam using a SEB file with the correct "Config Key" independently of the "Browser Exam Key" value.

**Screenshots**
![image](https://user-images.githubusercontent.com/67784821/86461080-5c664c80-bd21-11ea-9f5c-db399fb3b70c.png)

![image](https://user-images.githubusercontent.com/67784821/86460947-2d4fdb00-bd21-11ea-9987-a4778cb75012.png)

**Version Information**
 - OS: Windows 10 Professional, Version 2004
 - SEB-Version: 2.4 and 3.0.1

**Additional Context**
The problem only occurs with the Config Key. It seems to work fine with the "Browser Exame Key". The last key is not useful since our students have different OSs (Windows, Macs) with different versions of SEB

**Comment by danschlet** [comment]
The Config Key cannot be used in the same way as the Browser Exam Key. The LMS or exam system must explicitly support the Config Key, and in most cases this key would be generated automatically by the LMS together with the exam settings itself, so would not have to copy-paste the key manually like it's the case with the Browser Exam Key.

In the case of Moodle, version 3.9 has support for the automatic generating of SEB exam configs and the Config Key built in. You can also install the new SEB Moodle quiz access plugin in Moodle 3.7 and 3.8, see https://github.com/catalyst/moodle-quizaccess_seb (its also available in the Moodle plugin directory). Please search Moodle.org for documentation about the improved SEB integration in Moodle 3.9 and this new plugin.
